#!/usr/bin/env python3
"""Emit Grid<N>.bsv: an N x N grid of identical always-fire tiles.

Every tile is one parameterless (* synthesize *) module type (mkTile),
so the design is pure module replication: N*N instances of a single
small pipeline stage sharing one module type (no per-instance ports --
trs's compiled AOT path does not lower module input ports, and a
seed argument would silently demote the artifact to the interpreter).
Tiles are connected in row-major order -- tile (r,c) sends its output
FIFO east to (r,c+1); the last column sends south to (r+1,0); the
final tile wraps back to (0,0), closing a single ring that threads the
whole grid.  Per-tile identity comes from the TOP module: each link
rule XORs a distinct per-link constant ("twist") into the word it
forwards, so tile histories diverge by position while the tile module
itself stays identical everywhere.

Tile contents (the spec of the benchmark, keep stable across N):
  - 2 plain Regs (s1, s2): pipeline state, updated every cycle
  - 1 ConfigReg (acc): the accumulator sampled by the top-level
    checksum rule (ConfigReg so the harvest rule reads it without
    adding scheduling constraints against the tile's step rule)
  - 1 unguarded FIFO (mkUGFIFOF, depth 2): the link to the east/south
    neighbor.  Unguarded methods keep every rule free of implicit
    conditions; explicit notFull/notEmpty muxes keep the data
    deterministic (a shared constant flows until the ring warms up).
  - 1 DWire input (default = golden-ratio constant): the neighbor's
    data arrives via a conditional put(); the DWire default keeps the
    datapath total.

Every rule except the top-level harvest rule carries
(* fire_when_enabled, no_implicit_conditions *): bsc rejects the
design if anything stops being always-fire, which is the point -- the
benchmark measures replicated always-fire scaling.

Arithmetic per tile per cycle: xor / add / rotate on Bit#(32)
(golden-ratio constants), so a cycle does real work and the checksum
is sensitive to every tile's history.  Output is deterministic: the
single $display of the diagonal-XOR checksum at the given cycle.

v3 tiles (default): each tile RUNS A SMALL PROGRAM -- a 12-entry
case-ROM of packed {op[2:0], rs[2:0], rd[2:0]} micro-instructions, a
PC, an 8-entry architectural RegFile (mkRegFileFull: full-range, so
reads stay on the compiler's pure fast path), and opcode
case-dispatch with genuinely conditional writeback and send.  The
link rules drain tiles through an ActionValue oTake() called inside
a conditional arm of the packed rules -- the def-inside-conditional-
arm and ActionValue classes the compiler sealed in 09cb6a86, put in
the hot path.  --tile v2 keeps the previous mixing-pipeline tile.

Usage:
  gen_grid.py N [-o FILE] [--cycles C] [--tile v2|v3]

Default output file is Grid<N>.bsv in the current directory; the top
module is sysGrid<N>.
"""

import argparse
import sys

GOLD = 0x9E3779B9  # 2^32 / golden ratio
MIX = 0x7F4A7C15   # splitmix64 constant (low word)


def twist(i):
    """Per-link 32-bit constant (distinct, deterministic)."""
    return (i * GOLD + MIX) & 0xFFFFFFFF


HEADER = """\
// Grid{n}.bsv -- generated by gen_grid.py {n} --cycles {cycles}; do not edit.
// {n} x {n} = {m} replicated tiles, always-fire, self-checking at cycle {cycles}.

import FIFOF :: *;
import ConfigReg :: *;
import RegFile :: *;

interface Tile;
   method Bool     oValid;
   method Bit#(32) oData;
   method Action   oDeq;
   method Action   put(Bit#(32) v);
   method Bit#(32) accVal;
endinterface

(* synthesize, always_ready *)
module mkTile(Tile);
   // v2 (Ravi): richer unit behind a HARD SYNTHESIS BOUNDARY —
   // 4-stage mixing pipeline, a 16-entry RegFile history (exercises
   // the inline sub/upd fast paths), a multiply, and the link FIFO.
   // Always-fire throughout; RegFile reads are gated by a saturating
   // warm-up counter so uninitialized entries never reach the
   // checksum (determinism across simulators).
   Wire#(Bit#(32))  inw  <- mkDWire(32'h{gold:08x});
   Reg#(Bit#(32))   s1   <- mkReg(0);
   Reg#(Bit#(32))   s2   <- mkReg(1);
   Reg#(Bit#(32))   s3   <- mkReg(32'h{mix:08x});
   Reg#(Bit#(32))   s4   <- mkReg(3);
   Reg#(Bit#(32))   acc  <- mkConfigReg(0);
   RegFile#(Bit#(4), Bit#(32)) hist <- mkRegFileFull;
   Reg#(Bit#(4))    hptr <- mkReg(0);
   Reg#(Bit#(5))    warm <- mkReg(0);
   FIFOF#(Bit#(32)) fout <- mkUGFIFOF;

   (* fire_when_enabled, no_implicit_conditions *)
   rule step;
      Bit#(32) x  = inw;
      Bit#(32) r1 = {{ x[30:0], x[31] }};                 // rotl 1
      Bit#(32) h0 = hist.sub(hptr);
      Bit#(32) h  = (warm[4] == 1) ? h0 : 32'h0;
      Bit#(32) y0 = (s1 ^ r1) + s2;
      Bit#(32) y1 = y0 * 32'h0000_9E37;                   // odd mult
      Bit#(32) y  = (y1 ^ {{ s3[24:0], s3[31:25] }}) + s4; // rotl 7
      s1   <= x + 32'h{gold:08x};
      s2   <= {{ s2[28:0], s2[31:29] }} ^ x;              // rotl 3
      s3   <= y0 ^ h;
      s4   <= (s4 + 32'h{mix:08x}) ^ {{ y0[15:0], y0[31:16] }};
      hist.upd(hptr, y ^ h);
      hptr <= hptr + 1;
      warm <= (warm[4] == 1) ? warm : warm + 1;
      acc  <= (acc ^ y ^ h) + 32'h01000193;               // FNV prime
      if (fout.notFull) fout.enq(y ^ h);
   endrule

   method Bool     oValid = fout.notEmpty;
   method Bit#(32) oData  = fout.first;
   method Action oDeq;
      fout.deq;
   endmethod
   method Action put(Bit#(32) v);
      inw <= v;
   endmethod
   method Bit#(32) accVal = acc;
endmodule
"""

HEADER_V3 = """\
// Grid{n}.bsv -- generated by gen_grid.py {n} --tile v3 --cycles {cycles}; do not edit.
// {n} x {n} = {m} program tiles, always-fire, self-checking at cycle {cycles}.

import FIFOF :: *;
import ConfigReg :: *;
import RegFile :: *;

interface Tile;
   method Bool     oValid;
   method ActionValue#(Bit#(32)) oTake;
   method Action   put(Bit#(32) v);
   method Bit#(32) accVal;
endinterface

(* synthesize, always_ready *)
module mkTile(Tile);
   // v3 (Ravi): each tile runs a SMALL PROGRAM behind the synthesis
   // boundary -- 12-entry case-ROM of {{op,rs,rd}} micro-instructions,
   // PC, 8-entry architectural RegFile (full range: reads stay on the
   // pure fast path), opcode case-dispatch with conditional writeback
   // and send.  Always-fire; RegFile reads warm-gated so
   // uninitialized entries never reach the checksum.
   Wire#(Bit#(32))  inw  <- mkDWire(32'h{gold:08x});
   Reg#(Bit#(4))    pc   <- mkReg(0);
   Reg#(Bit#(32))   r0   <- mkReg(0);
   Reg#(Bit#(32))   r1   <- mkReg(1);
   Reg#(Bit#(32))   acc  <- mkConfigReg(0);
   RegFile#(Bit#(3), Bit#(32)) rf <- mkRegFileFull;
   Reg#(Bit#(4))    warm <- mkReg(0);
   FIFOF#(Bit#(32)) fout <- mkUGFIFOF;

   function Bit#(9) rom(Bit#(4) i);
      case (i)
         4'd0:  return {{{{ 3'd0, 3'd0, 3'd1 }}}};
         4'd1:  return {{{{ 3'd1, 3'd1, 3'd2 }}}};
         4'd2:  return {{{{ 3'd2, 3'd2, 3'd3 }}}};
         4'd3:  return {{{{ 3'd3, 3'd3, 3'd4 }}}};
         4'd4:  return {{{{ 3'd4, 3'd4, 3'd5 }}}};
         4'd5:  return {{{{ 3'd5, 3'd5, 3'd6 }}}};
         4'd6:  return {{{{ 3'd6, 3'd6, 3'd7 }}}};
         4'd7:  return {{{{ 3'd7, 3'd7, 3'd0 }}}};
         4'd8:  return {{{{ 3'd2, 3'd1, 3'd3 }}}};
         4'd9:  return {{{{ 3'd5, 3'd3, 3'd2 }}}};
         4'd10:  return {{{{ 3'd1, 3'd4, 3'd6 }}}};
         4'd11:  return {{{{ 3'd3, 3'd6, 3'd0 }}}};
         default: return {{ 3'd7, 3'd0, 3'd0 }};
      endcase
   endfunction

   (* fire_when_enabled, no_implicit_conditions *)
   rule exec;
      Bit#(9)  ins = rom(pc);
      Bit#(3)  op  = ins[8:6];
      Bit#(3)  rs  = ins[5:3];
      Bit#(3)  rd  = ins[2:0];
      Bit#(32) x   = inw;
      Bit#(32) h0  = rf.sub(rs);
      Bit#(32) h   = (warm[3] == 1) ? h0 : 32'h0;
      Bit#(32) res;
      case (op)
         3'd0: res = (r0 ^ x) + 32'h{gold:08x};
         3'd1: res = h + {{ r1[28:0], r1[31:29] }};             // rotl 3
         3'd2: res = (h ^ r0) * 32'h0000_9E37;                  // odd mult
         3'd3: res = {{ h[15:0], h[31:16] }} ^ r1;              // swap
         3'd4: res = h + (x ^ r1);
         3'd5: res = (r0 | 32'h1) + (h ^ 32'h{mix:08x});
         3'd6: res = r0 ^ {{ h[24:0], h[31:25] }};              // rotl 7
         default: res = h + r0 + x;
      endcase
      // program-shaped control flow: conditional writeback + send
      if (op != 3'd3) rf.upd(rd, res);
      else            rf.upd(rd, res ^ x);
      if (op == 3'd5 && fout.notFull) fout.enq(res);
      r0   <= res;
      // absorb the link input EVERY cycle: puts land on a DWire,
      // so divergence must be captured durably the same instant
      r1   <= ((op == 3'd2) ? (res ^ r1) : (r1 + 32'h{mix:08x})) ^ x;
      pc   <= (pc == 4'd11) ? 0 : pc + 1;
      warm <= (warm[3] == 1) ? warm : warm + 1;
      acc  <= (acc ^ res) + 32'h01000193;                       // FNV prime
   endrule

   method Bool oValid = fout.notEmpty;
   method ActionValue#(Bit#(32)) oTake;
      fout.deq;
      return fout.first;
   endmethod
   method Action put(Bit#(32) v);
      inw <= v;
   endmethod
   method Bit#(32) accVal = acc;
endmodule
"""


def emit(n, cycles, link_rules, out, tile='v3'):
    m = n * n
    w = out.write
    hdr = HEADER_V3 if tile == 'v3' else HEADER
    w(hdr.format(n=n, m=m, cycles=cycles, gold=GOLD, mix=MIX))
    w("\n(* synthesize *)\n")
    w("module sysGrid%d(Empty);\n" % n)
    w("   // %d tiles, row-major: t<i> is (row i/%d, col i%%%d); tile i\n"
      % (m, n, n))
    w("   // sends to tile (i+1) %% %d (east; end of row goes south to\n" % m)
    w("   // the next row's column 0; the last tile wraps to (0,0)).\n")
    for i in range(m):
        w("   Tile t%d <- mkTile;   // (%d,%d)\n" % (i, i // n, i % n))
    w("\n   Reg#(Bit#(32)) cyc <- mkReg(0);\n")
    w("""
   (* fire_when_enabled, no_implicit_conditions *)
   rule tick;
      cyc <= cyc + 1;
   endrule
""")
    # the one conditioned rule: sample the diagonal, print, finish
    w("\n   rule harvest (cyc == %d);\n" % cycles)
    w("      Bit#(32) cs = 0;\n")
    for r in range(n):
        i = r * n + r
        w("      cs = cs ^ t%d.accVal;   // (%d,%d)\n" % (i, r, r))
    w('      $display("grid %%0d x %%0d cycle %%0d checksum %%h", %d, %d, cyc, cs);\n'
      % (n, n))
    w("      $finish(0);\n")
    w("   endrule\n")
    # links: a FEW LARGE rules with many actions instead of m rules —
    # bsc's inferred scheduling is O(rules^2), and 1024 top-level link
    # rules measured 71s of frontend; each tile pair is touched by
    # exactly one action (deq on i, put on j), so packing links into
    # one atomic rule is conflict-free.  Per-link twists keep tile
    # histories position-distinct.
    per = max(1, (m + link_rules - 1) // link_rules)
    for k in range(link_rules):
        lo, hi = k * per, min((k + 1) * per, m)
        if lo >= hi:
            break
        w("\n   (* fire_when_enabled, no_implicit_conditions *)\n")
        w("   rule links_%d;   // links %d..%d\n" % (k, lo, hi - 1))
        for i in range(lo, hi):
            j = (i + 1) % m
            w("      if (t%d.oValid) begin\n" % i)
            if tile == 'v3':
                # ActionValue result bound INSIDE the conditional arm
                w("         let v%d <- t%d.oTake;\n" % (i, i))
                w("         t%d.put(v%d ^ 32'h%08x);\n" % (j, i, twist(j)))
            else:
                w("         t%d.put(t%d.oData ^ 32'h%08x);\n" % (j, i, twist(j)))
                w("         t%d.oDeq;\n" % i)
            w("      end\n")
        w("   endrule\n")
    w("endmodule\n")


def main():
    ap = argparse.ArgumentParser(
        description="emit Grid<N>.bsv: N x N replicated always-fire tiles")
    ap.add_argument("n", type=int, help="grid edge (N x N tiles)")
    ap.add_argument("-o", "--out", default="",
                    help="output file (default Grid<N>.bsv; '-' for stdout)")
    ap.add_argument("--link-rules", type=int, default=4,
                    help="number of large link rules the transfers are "
                    "packed into (bsc scheduling is O(rules^2))")
    ap.add_argument("--tile", choices=["v2", "v3"], default="v3",
                    help="tile flavor: v3 program tiles (default) or "
                    "the v2 mixing pipeline")
    ap.add_argument("--cycles", type=int, default=1000,
                    help="cycle at which the checksum prints and the "
                    "simulation finishes (default 1000)")
    args = ap.parse_args()
    if args.n < 1:
        ap.error("N must be >= 1")
    path = args.out or ("Grid%d.bsv" % args.n)
    if path == "-":
        emit(args.n, args.cycles, args.link_rules, sys.stdout, args.tile)
    else:
        with open(path, "w") as f:
            emit(args.n, args.cycles, args.link_rules, f, args.tile)


if __name__ == "__main__":
    main()
