#!/usr/bin/env python3
"""M0 shim generator: BviContract + verilator metadata -> shim.cpp.

The shim implements the engine-neutral C ABI from the design (v4 sec 5.2):
  vlt_new(inst_path, argc, argv) / vlt_free / vlt_set(h, port_idx, limbs)
  vlt_get(h, port_idx, limbs) / vlt_eval / vlt_set_time / vlt_finished
  vlt_contract / vlt_set_output_cb
Per-instance VerilatedContext; Verilated::threadContextp before every
entry; final() exactly once in vlt_free; VL_PRINTF redirect and vl_fatal
containment via compile defines (driver passes them to verilator).
Port access is generated from the metadata's origName->name map so user
identifiers that Verilator mangles still bind (M0 proves the mechanism;
the counter fixture's names are unmangled).
"""
import hashlib
import json
import sys
from pathlib import Path


def ctype_for(width):
    if width <= 8: return "CData"
    if width <= 16: return "SData"
    if width <= 32: return "IData"
    if width <= 64: return "QData"
    return None  # VlWide


def gen(contract, meta, out_cpp):
    top = contract["verilog_name"]
    by_orig = {p["orig_name"]: p for p in meta["ports"]}
    ports = []
    for idx, cp in enumerate(contract["ports"]):
        mp = by_orig.get(cp["name"])
        if mp is None:
            raise SystemExit(f"contract port {cp['name']!r} not in model")
        if mp["width"] != cp["width"]:
            raise SystemExit(f"width mismatch {cp['name']}: contract "
                             f"{cp['width']} vs model {mp['width']}")
        if mp["dir"] != cp["dir"]:
            raise SystemExit(f"dir mismatch {cp['name']}")
        ports.append((idx, cp, mp))

    chash = hashlib.sha256(
        json.dumps(contract, sort_keys=True).encode()).hexdigest()[:16]
    contract_blob = json.dumps({"contract": contract, "hash": chash}
                               ).replace('\\', r'\\').replace('"', r'\"')

    set_cases, get_cases = [], []
    for idx, cp, mp in ports:
        member = mp["name"]  # verilator's (possibly mangled) member name
        w = cp["width"]
        ct = ctype_for(w)
        if cp["dir"] == "input":
            if ct:
                set_cases.append(
                    f"    case {idx}: h->model->{member} = ({ct})limbs[0]; break;")
            else:
                words = (w + 31) // 32
                set_cases.append(
                    f"    case {idx}: for (int i = 0; i < {words}; i++) "
                    f"h->model->{member}[i] = (IData)(limbs[i/2] >> ((i%2)*32)); break;")
        if ct:
            get_cases.append(
                f"    case {idx}: limbs[0] = (uint64_t)h->model->{member}; break;")
        else:
            words = (w + 31) // 32
            get_cases.append(
                f"    case {idx}: {{ for (int i = 0; i < {(w+63)//64}; i++) limbs[i] = 0; "
                f"for (int i = 0; i < {words}; i++) "
                f"limbs[i/2] |= ((uint64_t)h->model->{member}[i]) << ((i%2)*32); }} break;")

    code = f'''// Generated by shimgen.py -- M0 spike shim for {top}
#include "V{top}.h"
#include "verilated.h"
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <stdexcept>

typedef void (*trs_output_cb)(void* ctx, const char* text);
static trs_output_cb g_out_cb = nullptr;
static void* g_out_ctx = nullptr;
static char g_fatal_msg[512];
static bool g_fatal = false;

extern "C" int trs_vlt_printf(const char* fmt, ...) {{
    char buf[4096];
    va_list ap; va_start(ap, fmt);
    int n = vsnprintf(buf, sizeof buf, fmt, ap);
    va_end(ap);
    if (g_out_cb) g_out_cb(g_out_ctx, buf); else fwrite(buf, 1, n, stdout);
    return n;
}}

// vl_fatal containment (driver compiles everything with -DVL_USER_FATAL).
void vl_fatal(const char* filename, int linenum, const char* hier,
              const char* msg) VL_MT_UNSAFE {{
    snprintf(g_fatal_msg, sizeof g_fatal_msg, "%s:%d %s: %s",
             filename ? filename : "?", linenum, hier ? hier : "", msg);
    g_fatal = true;
    throw std::runtime_error(g_fatal_msg);
}}

struct Handle {{
    VerilatedContext* ctx;
    V{top}* model;
    bool finaled;
}};

#define ENTER(h) Verilated::threadContextp((h)->ctx)
#define GUARD_BEGIN try {{
#define GUARD_END   }} catch (const std::exception&) {{ return -1; }} return 0;

extern "C" {{

void* vlt_new(const char* inst_path, int argc, const char** argv) {{
    try {{
        Handle* h = new Handle();
        h->ctx = new VerilatedContext();
        if (argc > 0) h->ctx->commandArgs(argc, argv);
        Verilated::threadContextp(h->ctx);
        h->model = new V{top}(h->ctx, inst_path ? inst_path : "{top}");
        h->finaled = false;
        return h;
    }} catch (const std::exception&) {{ return nullptr; }}
}}

int vlt_free(void* vh) {{
    Handle* h = (Handle*)vh; if (!h) return 0;
    ENTER(h);
    GUARD_BEGIN
    if (!h->finaled) {{ h->model->final(); h->finaled = true; }}
    delete h->model; delete h->ctx; delete h;
    GUARD_END
}}

int vlt_set(void* vh, uint32_t port, const uint64_t* limbs) {{
    Handle* h = (Handle*)vh; ENTER(h);
    GUARD_BEGIN
    switch (port) {{
{chr(10).join(set_cases)}
    default: return -2;
    }}
    GUARD_END
}}

int vlt_get(void* vh, uint32_t port, uint64_t* limbs) {{
    Handle* h = (Handle*)vh; ENTER(h);
    GUARD_BEGIN
    switch (port) {{
{chr(10).join(get_cases)}
    default: return -2;
    }}
    GUARD_END
}}

int vlt_eval(void* vh) {{
    Handle* h = (Handle*)vh; ENTER(h);
    GUARD_BEGIN
    h->model->eval();
    GUARD_END
}}

int vlt_set_time(void* vh, uint64_t t) {{
    Handle* h = (Handle*)vh; ENTER(h);
    GUARD_BEGIN
    h->ctx->time(t);
    GUARD_END
}}

int vlt_finished(void* vh) {{
    Handle* h = (Handle*)vh; ENTER(h);
    return (h->ctx->gotFinish() ? 1 : 0) | (g_fatal ? 2 : 0);
}}

const char* vlt_contract(void) {{
    return "{contract_blob}";
}}

const char* vlt_fatal_msg(void) {{ return g_fatal ? g_fatal_msg : ""; }}

void vlt_set_output_cb(trs_output_cb cb, void* cbctx) {{
    g_out_cb = cb; g_out_ctx = cbctx;
}}

}} // extern "C"
'''
    Path(out_cpp).write_text(code)
    return chash


if __name__ == "__main__":
    contract = json.loads(Path(sys.argv[1]).read_text())
    meta = json.loads(Path(sys.argv[2]).read_text())
    print(gen(contract, meta, sys.argv[3]))
