//! Shim generator: BviContract + model metadata -> shim.cpp
//! implementing the engine-neutral C ABI (design v4 sec 5.2 item 3):
//!   vlt_new(inst_path, argc, argv) / vlt_free / vlt_set(h, port, limbs)
//!   vlt_get / vlt_eval / vlt_set_time / vlt_advance / vlt_finished
//!   vlt_contract / vlt_fatal_msg / vlt_set_output_cb
//! Per-instance VerilatedContext; threadContextp before every entry;
//! final() exactly once in vlt_free; VL_PRINTF redirect and vl_fatal
//! containment ride compile defines the builder passes.
//!
//! Port access is generated from the metadata's origName -> name map so
//! identifiers Verilator mangles still bind.  Ports are addressed by
//! their CONTRACT index; (*inhigh*) enables (BVI_PROP_INHIGH) have no
//! physical port and get no case.

use trs_ir::bvi::{BviContract, BviDir, BviPortKind, BVI_PROP_INHIGH};

use crate::meta::{MetaPort, ModelMeta, PortDir};
use crate::{sha256, VltError};

/// Bumped whenever the generated shim's shape or the C ABI changes;
/// part of the cache class key.
pub const SHIMGEN_REV: u32 = 4;

fn ctype_for(width: u32) -> Option<&'static str> {
    match width {
        0..=8 => Some("CData"),
        9..=16 => Some("SData"),
        17..=32 => Some("IData"),
        33..=64 => Some("QData"),
        _ => None, // VlWide
    }
}

/// Deterministic JSON of the contract (embedded via vlt_contract; its
/// sha256[:16] is the load-time identity check).
pub fn contract_json(c: &BviContract, strings: &[String]) -> String {
    let s = |id: u32| -> String {
        let raw = strings.get(id as usize).map(String::as_str).unwrap_or("");
        json_escape(raw)
    };
    let mut out = String::new();
    out.push_str(&format!("{{\"verilog_name\":\"{}\",\"ports\":[", s(c.verilog_name)));
    for (i, p) in c.ports.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        out.push_str(&format!(
            "{{\"name\":\"{}\",\"width\":{},\"dir\":\"{}\",\"kind\":\"{:?}\",\"props\":{}}}",
            s(p.name),
            p.width,
            match p.dir {
                BviDir::Input => "input",
                BviDir::Output => "output",
            },
            p.kind,
            p.props
        ));
    }
    out.push_str("],\"methods\":[");
    for (i, m) in c.methods.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        out.push_str(&format!(
            "{{\"name\":\"{}\",\"kind\":\"{:?}\",\"self_sbr\":{}}}",
            s(m.name),
            m.kind,
            m.self_sbr
        ));
    }
    out.push_str("]}");
    out
}

fn json_escape(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

/// The forced-include declaration for the VL_PRINTF redirect:
/// verilated.cpp itself calls VL_PRINTF, so the symbol must be declared
/// before any Verilator header lands.
pub const PRINTF_DECL_H: &str = "\
// Generated by trs-vlt: declaration for -DVL_PRINTF=trs_vlt_printf.
#pragma once
#ifdef __cplusplus
extern \"C\" int trs_vlt_printf(const char* fmt, ...);
#else
extern int trs_vlt_printf(const char* fmt, ...);
#endif
";

/// Generate shim.cpp.  Checks the contract against the model metadata:
/// every physical contract port must exist (by origName), with matching
/// width and direction, and the model must offer no primary port the
/// contract does not know (an unknown port would float or drive
/// nothing -- exactly the contract/model mismatch the design refuses).
pub fn generate(
    c: &BviContract,
    strings: &[String],
    meta: &ModelMeta,
) -> Result<(String, String), VltError> {
    let sname = |id: u32| strings.get(id as usize).map(String::as_str).unwrap_or("");
    let top = sname(c.verilog_name).to_string();

    let find = |orig: &str| -> Option<&MetaPort> {
        meta.ports.iter().find(|p| p.orig_name == orig)
    };

    let mut set_cases = String::new();
    let mut get_cases = String::new();
    let mut seen = vec![false; meta.ports.len()];

    for (idx, p) in c.ports.iter().enumerate() {
        let pn = sname(p.name);
        if p.kind == BviPortKind::Enable && (p.props & BVI_PROP_INHIGH) != 0 {
            // no physical port; never matched against the model
            continue;
        }
        let mp = find(pn).ok_or_else(|| {
            VltError::refuse(
                "contract-mismatch",
                format!("contract port '{pn}' not found on model '{top}'"),
            )
        })?;
        let mp_index = meta
            .ports
            .iter()
            .position(|q| std::ptr::eq(q, mp))
            .unwrap_or(usize::MAX);
        if mp_index < seen.len() {
            seen[mp_index] = true;
        }
        if mp.width != p.width {
            return Err(VltError::refuse(
                "contract-mismatch",
                format!(
                    "port '{pn}': contract width {} vs model width {}",
                    p.width, mp.width
                ),
            ));
        }
        let want = match p.dir {
            BviDir::Input => PortDir::Input,
            BviDir::Output => PortDir::Output,
        };
        if mp.dir != want {
            return Err(VltError::refuse(
                "contract-mismatch",
                format!("port '{pn}': direction differs between contract and model"),
            ));
        }
        let member = &mp.name;
        let w = p.width;
        if p.dir == BviDir::Input {
            match ctype_for(w) {
                Some(ct) => set_cases.push_str(&format!(
                    "    case {idx}: h->model->{member} = ({ct})limbs[0]; break;\n"
                )),
                None => {
                    let words = (w + 31) / 32;
                    set_cases.push_str(&format!(
                        "    case {idx}: for (int i = 0; i < {words}; i++) \
                         h->model->{member}[i] = (IData)(limbs[i/2] >> ((i%2)*32)); break;\n"
                    ));
                }
            }
        }
        match ctype_for(w) {
            Some(_) => get_cases.push_str(&format!(
                "    case {idx}: limbs[0] = (uint64_t)h->model->{member}; break;\n"
            )),
            None => {
                let words = (w + 31) / 32;
                let limbs = (w + 63) / 64;
                get_cases.push_str(&format!(
                    "    case {idx}: {{ for (int i = 0; i < {limbs}; i++) limbs[i] = 0; \
                     for (int i = 0; i < {words}; i++) \
                     limbs[i/2] |= ((uint64_t)h->model->{member}[i]) << ((i%2)*32); }} break;\n"
                ));
            }
        }
    }

    let extras: Vec<&str> = meta
        .ports
        .iter()
        .zip(seen.iter())
        .filter(|(_, s)| !**s)
        .map(|(p, _)| p.orig_name.as_str())
        .collect();
    if !extras.is_empty() {
        return Err(VltError::refuse(
            "contract-mismatch",
            format!(
                "model '{top}' has primary ports the contract does not declare: {}",
                extras.join(", ")
            ),
        ));
    }

    let cjson = contract_json(c, strings);
    let chash = sha256::digest_hex(cjson.as_bytes())[..16].to_string();
    let blob = cjson.replace('\\', "\\\\").replace('"', "\\\"");

    // vlt_advance: bring the model's time to `to`.  Timing models
    // (--timing build; the model has delay constructs) drain internal
    // delayed events strictly BEFORE `to` -- each drained slot is one
    // eval at that slot's time -- and report the drained count so the
    // caller knows outputs may have moved with no input change.  Events
    // scheduled exactly AT `to` fire in the caller's next eval at `to`
    // (or the next advance), matching the reference simulators' region
    // ordering: a delayed NBA landing at T updates after active-region
    // reads at T.  Non-timing models have no internal events; advance
    // is a plain time set.
    let advance_body = if meta.has_delay {
        "    uint64_t n = 0;\n\
         \x20   while (h->model->eventsPending() && h->model->nextTimeSlot() < to) {\n\
         \x20       h->ctx->time(h->model->nextTimeSlot());\n\
         \x20       h->model->eval();\n\
         \x20       n++;\n\
         \x20   }\n\
         \x20   h->ctx->time(to);\n\
         \x20   if (drained) *drained = n;\n"
            .to_string()
    } else {
        "    h->ctx->time(to);\n\
         \x20   if (drained) *drained = 0;\n"
            .to_string()
    };

    let code = format!(
        r#"// Generated by trs-vlt (shimgen rev {rev}) for {top}
#include "V{top}.h"
#include "verilated.h"
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <stdexcept>

typedef void (*trs_output_cb)(void* ctx, const char* text);
static trs_output_cb g_out_cb = nullptr;
static void* g_out_ctx = nullptr;
static char g_fatal_msg[512];
static bool g_fatal = false;

extern "C" int trs_vlt_printf(const char* fmt, ...) {{
    char buf[4096];
    va_list ap; va_start(ap, fmt);
    int n = vsnprintf(buf, sizeof buf, fmt, ap);
    va_end(ap);
    if (g_out_cb) g_out_cb(g_out_ctx, buf); else fwrite(buf, 1, n, stdout);
    return n;
}}

// vl_finish (built with -DVL_USER_FINISH): set the context's finish
// flag SILENTLY -- the reference Bluesim prints nothing for $finish,
// and byte parity with its goldens is the oracle contract (Verilator's
// default prints "- <file>: Verilog $finish").
void vl_finish(const char* filename, int linenum, const char* hier)
    VL_MT_UNSAFE {{
    (void)filename; (void)linenum; (void)hier;
    Verilated::threadContextp()->gotFinish(true);
}}

// vl_fatal containment (built with -DVL_USER_FATAL): $fatal/$stop and
// assertion failures become error returns, never a host abort().
void vl_fatal(const char* filename, int linenum, const char* hier,
              const char* msg) VL_MT_UNSAFE {{
    snprintf(g_fatal_msg, sizeof g_fatal_msg, "%s:%d %s: %s",
             filename ? filename : "?", linenum, hier ? hier : "", msg);
    g_fatal = true;
    throw std::runtime_error(g_fatal_msg);
}}

struct Handle {{
    VerilatedContext* ctx;
    V{top}* model;
    bool finaled;
}};

#define ENTER(h) Verilated::threadContextp((h)->ctx)
#define GUARD_BEGIN try {{
#define GUARD_END   }} catch (const std::exception&) {{ return -1; }} return 0;

extern "C" {{

void* vlt_new(const char* inst_path, int argc, const char** argv) {{
    try {{
        Handle* h = new Handle();
        h->ctx = new VerilatedContext();
        // always, even with argc==0: $test$plusargs errors if
        // commandArgs was never called on the context
        h->ctx->commandArgs(argc, argv);
        Verilated::threadContextp(h->ctx);
        h->model = new V{top}(h->ctx, inst_path ? inst_path : "{top}");
        h->finaled = false;
        return h;
    }} catch (const std::exception&) {{ return nullptr; }}
}}

int vlt_free(void* vh) {{
    Handle* h = (Handle*)vh; if (!h) return 0;
    ENTER(h);
    GUARD_BEGIN
    if (!h->finaled) {{ h->model->final(); h->finaled = true; }}
    delete h->model; delete h->ctx; delete h;
    GUARD_END
}}

int vlt_set(void* vh, uint32_t port, const uint64_t* limbs) {{
    Handle* h = (Handle*)vh; ENTER(h);
    GUARD_BEGIN
    switch (port) {{
{set_cases}    default: return -2;
    }}
    GUARD_END
}}

int vlt_get(void* vh, uint32_t port, uint64_t* limbs) {{
    Handle* h = (Handle*)vh; ENTER(h);
    GUARD_BEGIN
    switch (port) {{
{get_cases}    default: return -2;
    }}
    GUARD_END
}}

int vlt_eval(void* vh) {{
    Handle* h = (Handle*)vh; ENTER(h);
    GUARD_BEGIN
    h->model->eval();
    GUARD_END
}}

int vlt_set_time(void* vh, uint64_t t) {{
    Handle* h = (Handle*)vh; ENTER(h);
    GUARD_BEGIN
    h->ctx->time(t);
    GUARD_END
}}

int vlt_advance(void* vh, uint64_t to, uint64_t* drained) {{
    Handle* h = (Handle*)vh; ENTER(h);
    GUARD_BEGIN
{advance_body}    GUARD_END
}}

int vlt_finished(void* vh) {{
    Handle* h = (Handle*)vh; ENTER(h);
    return (h->ctx->gotFinish() ? 1 : 0) | (g_fatal ? 2 : 0);
}}

const char* vlt_contract(void) {{
    return "{{\"contract\":{blob},\"hash\":\"{chash}\"}}";
}}

const char* vlt_fatal_msg(void) {{ return g_fatal ? g_fatal_msg : ""; }}

void vlt_set_output_cb(trs_output_cb cb, void* cbctx) {{
    g_out_cb = cb; g_out_ctx = cbctx;
}}

}} // extern "C"
"#,
        rev = SHIMGEN_REV,
        top = top,
        set_cases = set_cases,
        get_cases = get_cases,
        advance_body = advance_body,
        blob = blob,
        chash = chash,
    );
    Ok((code, chash))
}
