
# Tests for higher-rank struct fields

test_veri_only HigherRank
test_veri_only Undefined
test_veri_only DeepSeqCond

# Use of a higher-rank member of an unininitialized struct value
# results in an expected error
compile_verilog_fail_error Uninitialized.bs G0028 1 sysUninitialized
if { $vtest == 1 } { compare_file Uninitialized.bs.bsc-vcomp-out }

# Use of a member of a higher-rank member of an uninitialized struct value
# gives an error mentioning the inner member
compile_verilog_fail_error UninitializedStruct.bs G0028 1 sysUninitializedStruct
if { $vtest == 1 } { compare_file UninitializedStruct.bs.bsc-vcomp-out }

# We can still piecewise-define members of a higher-rank member of a struct
test_c_veri_bsv UninitializedStructBSV
