#!/usr/bin/env python3
"""Emit Grid<N>.bsv: an N x N grid of identical always-fire tiles.

Every tile is one parameterless (* synthesize *) module type (mkTile),
so the design is pure module replication: N*N instances of a single
small pipeline stage sharing one module type (no per-instance ports --
bsim3's compiled AOT path does not lower module input ports, and a
seed argument would silently demote the artifact to the interpreter).
Tiles are connected in row-major order -- tile (r,c) sends its output
FIFO east to (r,c+1); the last column sends south to (r+1,0); the
final tile wraps back to (0,0), closing a single ring that threads the
whole grid.  Per-tile identity comes from the TOP module: each link
rule XORs a distinct per-link constant ("twist") into the word it
forwards, so tile histories diverge by position while the tile module
itself stays identical everywhere.

Tile contents (the spec of the benchmark, keep stable across N):
  - 2 plain Regs (s1, s2): pipeline state, updated every cycle
  - 1 ConfigReg (acc): the accumulator sampled by the top-level
    checksum rule (ConfigReg so the harvest rule reads it without
    adding scheduling constraints against the tile's step rule)
  - 1 unguarded FIFO (mkUGFIFOF, depth 2): the link to the east/south
    neighbor.  Unguarded methods keep every rule free of implicit
    conditions; explicit notFull/notEmpty muxes keep the data
    deterministic (a shared constant flows until the ring warms up).
  - 1 DWire input (default = golden-ratio constant): the neighbor's
    data arrives via a conditional put(); the DWire default keeps the
    datapath total.

Every rule except the top-level harvest rule carries
(* fire_when_enabled, no_implicit_conditions *): bsc rejects the
design if anything stops being always-fire, which is the point -- the
benchmark measures replicated always-fire scaling.

Arithmetic per tile per cycle: xor / add / rotate on Bit#(32)
(golden-ratio constants), so a cycle does real work and the checksum
is sensitive to every tile's history.  Output is deterministic: the
single $display of the diagonal-XOR checksum at the given cycle.

Usage:
  gen_grid.py N [-o FILE] [--cycles C]

Default output file is Grid<N>.bsv in the current directory; the top
module is sysGrid<N>.
"""

import argparse
import sys

GOLD = 0x9E3779B9  # 2^32 / golden ratio
MIX = 0x7F4A7C15   # splitmix64 constant (low word)


def twist(i):
    """Per-link 32-bit constant (distinct, deterministic)."""
    return (i * GOLD + MIX) & 0xFFFFFFFF


HEADER = """\
// Grid{n}.bsv -- generated by gen_grid.py {n} --cycles {cycles}; do not edit.
// {n} x {n} = {m} replicated tiles, always-fire, self-checking at cycle {cycles}.

import FIFOF :: *;
import ConfigReg :: *;

interface Tile;
   method Bool     oValid;
   method Bit#(32) oData;
   method Action   oDeq;
   method Action   put(Bit#(32) v);
   method Bit#(32) accVal;
endinterface

(* synthesize, always_ready *)
module mkTile(Tile);
   Wire#(Bit#(32))  inw  <- mkDWire(32'h{gold:08x});
   Reg#(Bit#(32))   s1   <- mkReg(0);
   Reg#(Bit#(32))   s2   <- mkReg(1);
   Reg#(Bit#(32))   acc  <- mkConfigReg(0);
   FIFOF#(Bit#(32)) fout <- mkUGFIFOF;

   (* fire_when_enabled, no_implicit_conditions *)
   rule step;
      Bit#(32) x = inw;
      Bit#(32) r = {{ x[30:0], x[31] }};        // rotl 1
      Bit#(32) y = (s1 ^ r) + s2;
      s1  <= x + 32'h{gold:08x};
      s2  <= {{ s2[28:0], s2[31:29] }} ^ x;     // rotl 3, xor
      acc <= (acc ^ y) + 32'h01000193;          // FNV prime
      if (fout.notFull) fout.enq(y);
   endrule

   method Bool     oValid = fout.notEmpty;
   method Bit#(32) oData  = fout.first;
   method Action oDeq;
      fout.deq;
   endmethod
   method Action put(Bit#(32) v);
      inw <= v;
   endmethod
   method Bit#(32) accVal = acc;
endmodule
"""


def emit(n, cycles, out):
    m = n * n
    w = out.write
    w(HEADER.format(n=n, m=m, cycles=cycles, gold=GOLD))
    w("\n(* synthesize *)\n")
    w("module sysGrid%d(Empty);\n" % n)
    w("   // %d tiles, row-major: t<i> is (row i/%d, col i%%%d); tile i\n"
      % (m, n, n))
    w("   // sends to tile (i+1) %% %d (east; end of row goes south to\n" % m)
    w("   // the next row's column 0; the last tile wraps to (0,0)).\n")
    for i in range(m):
        w("   Tile t%d <- mkTile;   // (%d,%d)\n" % (i, i // n, i % n))
    w("\n   Reg#(Bit#(32)) cyc <- mkReg(0);\n")
    w("""
   (* fire_when_enabled, no_implicit_conditions *)
   rule tick;
      cyc <= cyc + 1;
   endrule
""")
    # the one conditioned rule: sample the diagonal, print, finish
    w("\n   rule harvest (cyc == %d);\n" % cycles)
    w("      Bit#(32) cs = 0;\n")
    for r in range(n):
        i = r * n + r
        w("      cs = cs ^ t%d.accVal;   // (%d,%d)\n" % (i, r, r))
    w('      $display("grid %%0d x %%0d cycle %%0d checksum %%h", %d, %d, cyc, cs);\n'
      % (n, n))
    w("      $finish(0);\n")
    w("   endrule\n")
    # link rules: forward with a distinct per-link twist so tile
    # histories diverge by grid position (the tile module itself is
    # identical everywhere; identity lives in the top's wiring)
    for i in range(m):
        j = (i + 1) % m
        w("""
   (* fire_when_enabled, no_implicit_conditions *)
   rule link_%d;
      if (t%d.oValid) begin
         t%d.put(t%d.oData ^ 32'h%08x);
         t%d.oDeq;
      end
   endrule
""" % (i, i, j, i, twist(j), i))
    w("endmodule\n")


def main():
    ap = argparse.ArgumentParser(
        description="emit Grid<N>.bsv: N x N replicated always-fire tiles")
    ap.add_argument("n", type=int, help="grid edge (N x N tiles)")
    ap.add_argument("-o", "--out", default="",
                    help="output file (default Grid<N>.bsv; '-' for stdout)")
    ap.add_argument("--cycles", type=int, default=1000,
                    help="cycle at which the checksum prints and the "
                    "simulation finishes (default 1000)")
    args = ap.parse_args()
    if args.n < 1:
        ap.error("N must be >= 1")
    path = args.out or ("Grid%d.bsv" % args.n)
    if path == "-":
        emit(args.n, args.cycles, sys.stdout)
    else:
        with open(path, "w") as f:
            emit(args.n, args.cycles, f)


if __name__ == "__main__":
    main()
