//! The BIR reference interpreter — DESIGN.md P1, the differential oracle.
//!
//! Executes the exported design directly: per (clock, edge) composition,
//! walk each (instance, segment) entry; at `Sched r` latch the rule's
//! CAN_FIRE (with ME inhibitors) and WILL_FIRE; at `Exec r` run the rule
//! body if its latched WILL_FIRE is set.  Rule bodies mutate state in
//! place; primitives implement the begin-of-cycle-snapshot semantics.
//! Correctness and clarity over speed, everywhere.

pub mod format;
pub mod prim;
pub mod value;

use std::collections::HashMap;

use trs_ir as ir;
use trs_ir::{Action, Design, Expr, PrimOp, SchedNode, Stmt, StrId};

mod bdpi;

use format::Arg;
use prim::Prim;
use value::Value;

// ===============
// Indexed design

struct ModIx {
    ir: usize, // index into design.modules
    ports: HashMap<StrId, (u32, ir::PortKind)>,
    defs: HashMap<StrId, usize>,
    rules: HashMap<StrId, usize>,
    methods: HashMap<StrId, usize>,
}

pub struct Interp {
    d: Design,
    /// Verilog file handles, mirroring VLFiles (dollar_display.cxx):
    /// one-arg $fopen returns a one-hot MCD key (slot 0 = stdout, first
    /// user file = 0x2, writes fan out to every set bit); two-arg $fopen
    /// returns 0x8000_0000+index with stdin/stdout/stderr preregistered
    /// (first user fd = 0x8000_0003)
    mcd_files: Vec<FSlot>,
    fd_files: Vec<FSlot>,
    /// per-key pushback stack for $ungetc; $fgetc pops from here first
    pushback: HashMap<u64, Vec<u8>>,
    /// runtime-created strings (PrimStringConcat results); string ids at
    /// or past the design table's length index into this arena
    dyn_strs: Vec<String>,
    /// dlopened user BDPI code (from the companion .bdpi.so)
    bdpi: Option<bdpi::Bdpi>,
    /// command-line +args (without the '+'), for $test$plusargs
    plusargs: Vec<String>,
    mods: Vec<ModIx>,
    mod_by_name: HashMap<StrId, usize>,
    /// instance path -> instance state index
    inst_by_path: HashMap<String, usize>,
    insts: Vec<Inst>,
    finished: Option<i32>,
    /// $fatal was called: the bluesim.tcl driver exits 1 in that case
    /// and 0 otherwise ($finish codes are not process exit codes)
    fataled: bool,
    cycle: u64,
    /// current simulation time (the time of the executing clock edge)
    now: u64,
    /// "<path>$CLK_OUT" -> waveform, captured from ClockGen instantiation
    /// args (bs_prim_mod_clockgen.h set_clk_0 -> bk_alter_clock)
    clockgen_waves: HashMap<String, Wave>,
    /// "<path>$CLK_OUT" -> initial level for dynamic clocks (MakeClock,
    /// ClockDiv, ClockInverter) whose edges are prim-triggered
    dynclk_init: HashMap<String, bool>,
    /// Reset network.  Node 0 is the top reset (kernel-driven: asserted
    /// at t=0, deasserted at t=2 after that instant's logic); other nodes
    /// are derived resets generated by reset primitives.  Rule bodies
    /// carry their own reset guards as exported Cond statements over the
    /// reset wire ports, so the interpreter only has to answer "is this
    /// reset wire asserted" and drive prim reset lines.
    rst_asserted: Vec<bool>,
    /// node -> (prim instance, reset-arg ordinal) subscriptions
    rst_subs: Vec<Vec<(usize, usize)>>,
    /// reset-generating prim instance -> the node its OUT_RST drives
    rstgen_out: HashMap<usize, usize>,
    /// deferred (end-of-timeslice) reset transitions, mirroring
    /// reset_at_end_of_timeslice in bs_prim_mod_resets.h
    rst_pending: Vec<(usize, bool)>,
    /// reset nodes asserted from time 0 (InitialReset outputs), broadcast
    /// at run() start once instantiation is complete
    initial_asserts: Vec<usize>,
}

/// One Verilog file-table slot (VLFiles keeps FILE*; the std streams are
/// distinguished so they are never closed and write to the right place).
enum FSlot {
    Stdin,
    Stdout,
    Stderr,
    File(std::fs::File),
    Closed,
}

/// A periodic clock waveform.  The default clock is LOW with first edge
/// at t=0, high 5 / low 5 (the generated model's bk_alter_clock call), so
/// posedges land at 0 (in reset), 10, 20, ...
#[derive(Clone, Copy)]
struct Wave {
    init_high: bool,
    delay: u64,
    hi: u64,
    lo: u64,
    /// bk_alter_clock has_initial_value: an extra one-shot edge at t=0 in
    /// the direction of the initial value, at PG_INITIAL priority (before
    /// regular t=0 edges).  True for ClockGen, false for the default CLK.
    has_init: bool,
}

/// How a clock's edges are produced: a periodic waveform, triggered at
/// runtime by a clock-generating primitive (bk_trigger_clock_edge), or
/// never (noClock and top-level input clocks with no waveform — the
/// kernel defines them with period 0 and they never fire).
#[derive(Clone, Copy)]
enum ClockSource {
    Wave(Wave),
    Triggered { init_high: bool, driver: usize },
    Never,
}

struct Inst {
    #[allow(dead_code)]
    path: String,
    kind: InstKind,
}

enum InstKind {
    User {
        module: usize, // ModIx index
        /// per-cycle latched defs (CAN_FIRE/WILL_FIRE at Sched, task temps)
        latched: HashMap<StrId, Value>,
        /// local child name -> instance index
        children: HashMap<StrId, usize>,
        /// module parameters, bound at instantiation (positional zip of
        /// the child's inputs with the parent's instantiation args)
        params: HashMap<StrId, Value>,
        /// string-valued parameters: port name -> design string id
        /// (kept as ids so dynamic muxes carry them as marker values)
        str_params: HashMap<StrId, StrId>,
        /// local reset wire name -> reset node (module reset inputs bound
        /// at instantiation; derived resets created by child reset prims)
        resets: HashMap<StrId, usize>,
        /// local clock-gate port name (e.g. CLK_GATE_gclk) -> the gate
        /// expression it was instantiated with, evaluated in the parent
        /// instance (mkGateSubstMap semantics)
        gates: HashMap<StrId, (usize, Expr)>,
        /// local input clock port name (e.g. CLK_gclk) -> the osc
        /// expression it was instantiated with, resolved in the parent
        /// instance (used to chase interface/laundered clocks to their
        /// driving oscillator)
        clk_binds: HashMap<StrId, (usize, Expr)>,
    },
    Prim(Box<dyn Prim>),
}

/// Evaluation context: method-argument frame plus body-local defs.
/// `memo` caches every def computed on demand (used while latching fire
/// conditions, where no actions can intervene); body execution instead
/// computes defs at their statement positions, which is what preserves
/// read-before-mutate semantics.
#[derive(Default)]
struct Ctx {
    frame: HashMap<StrId, Value>,
    locals: HashMap<StrId, Value>,
    memo: bool,
}

impl Interp {
    pub fn new(d: Design) -> Interp {
        let str_ids: HashMap<&str, StrId> = d
            .strings
            .iter()
            .enumerate()
            .map(|(i, s)| (s.as_str(), i as StrId))
            .collect();
        let mods: Vec<ModIx> = d
            .modules
            .iter()
            .enumerate()
            .map(|(i, m)| ModIx {
                ir: i,
                // module inputs, plus method argument ports and the EN_<meth>
                // enable ports their WILL_FIRE defs read — an uncalled
                // method's EN reads as 0 (see Expr::Port in eval)
                ports: m
                    .inputs
                    .iter()
                    .map(|p| (p.name, (p.width, p.kind)))
                    .chain(m.methods.iter().flat_map(|me| {
                        me.args
                            .iter()
                            .map(|a| (a.name, (a.width, a.kind)))
                            .chain(
                                str_ids
                                    .get(format!("EN_{}", d.strings[me.name as usize]).as_str())
                                    .map(|&en| (en, (1, ir::PortKind::MethodEnable))),
                            )
                            .collect::<Vec<_>>()
                    }))
                    .collect(),
                defs: m.defs.iter().enumerate().map(|(k, x)| (x.name, k)).collect(),
                rules: m.rules.iter().enumerate().map(|(k, x)| (x.name, k)).collect(),
                methods: m.methods.iter().enumerate().map(|(k, x)| (x.name, k)).collect(),
            })
            .collect();
        let mod_by_name: HashMap<StrId, usize> =
            d.modules.iter().enumerate().map(|(i, m)| (m.name, i)).collect();

        let mut it = Interp {
            d,
            mods,
            mod_by_name,
            inst_by_path: HashMap::new(),
            insts: Vec::new(),
            mcd_files: vec![FSlot::Stdout],
            fd_files: vec![FSlot::Stdin, FSlot::Stdout, FSlot::Stderr],
            pushback: HashMap::new(),
            dyn_strs: Vec::new(),
            bdpi: None,
            plusargs: Vec::new(),
            finished: None,
            fataled: false,
            cycle: 0,
            now: 0,
            clockgen_waves: HashMap::new(),
            dynclk_init: HashMap::new(),
            rst_asserted: vec![false],
            rst_subs: vec![Vec::new()],
            rstgen_out: HashMap::new(),
            rst_pending: Vec::new(),
            initial_asserts: Vec::new(),
        };
        let top_mod = it.mod_by_name[&it.d.top];
        // the top module's reset inputs are all the kernel-driven reset
        let top_binds: HashMap<StrId, usize> = it.d.modules[it.mods[top_mod].ir]
            .inputs
            .iter()
            .filter(|p| p.kind == ir::PortKind::Reset)
            .map(|p| (p.name, 0))
            .collect();
        it.instantiate(
            "".to_string(),
            top_mod,
            HashMap::new(),
            HashMap::new(),
            top_binds,
            HashMap::new(),
            HashMap::new(),
        );
        it
    }

    fn s(&self, id: StrId) -> &str {
        let n = self.d.strings.len();
        if (id as usize) < n {
            &self.d.strings[id as usize]
        } else {
            &self.dyn_strs[id as usize - n]
        }
    }

    /// Intern a runtime-created string (StringConcat) into the arena.
    fn intern_dyn(&mut self, text: String) -> StrId {
        self.dyn_strs.push(text);
        (self.d.strings.len() + self.dyn_strs.len() - 1) as StrId
    }

    /// The string id bound to a string-valued parameter of an instance,
    /// if any (used to forward string parameters down the hierarchy).
    fn str_param_of(&self, inst: usize, name: StrId) -> Option<StrId> {
        if let InstKind::User { str_params, .. } = &self.insts[inst].kind {
            str_params.get(&name).copied()
        } else {
            None
        }
    }

    fn instantiate(
        &mut self,
        path: String,
        module: usize,
        params: HashMap<StrId, Value>,
        str_params: HashMap<StrId, StrId>,
        reset_binds: HashMap<StrId, usize>,
        gate_binds: HashMap<StrId, (usize, Expr)>,
        clk_binds: HashMap<StrId, (usize, Expr)>,
    ) -> usize {
        let slot = self.insts.len();
        let mir = self.mods[module].ir;

        // resets generated inside this module (SyncReset/MakeReset/... 
        // children) appear in the module's reset list as fresh wire names;
        // give each its own node
        let mut resets = reset_binds;
        let wires: Vec<Expr> = self.d.modules[mir].resets.iter().map(|r| r.wire.clone()).collect();
        for w in wires {
            if let Expr::Port(name) = w {
                resets.entry(name).or_insert_with(|| {
                    self.rst_asserted.push(false);
                    self.rst_subs.push(Vec::new());
                    self.rst_asserted.len() - 1
                });
            }
        }
        let reset_map = resets.clone();

        self.insts.push(Inst {
            path: path.clone(),
            kind: InstKind::User {
                module,
                latched: HashMap::new(),
                children: HashMap::new(),
                params,
                str_params,
                resets,
                gates: gate_binds,
                clk_binds,
            },
        });
        self.inst_by_path.insert(path.clone(), slot);

        let child_specs: Vec<(StrId, ir::InstanceKind, Vec<Expr>)> = self.d.modules[mir]
            .instances
            .iter()
            .map(|i| (i.name, i.kind.clone(), i.args.clone()))
            .collect();

        for (name, kind, args) in child_specs {
            let cpath = if path.is_empty() {
                self.s(name).to_string()
            } else {
                format!("{}.{}", path, self.s(name))
            };
            let cidx = match kind {
                ir::InstanceKind::Module(mname) => {
                    let cmod = *self
                        .mod_by_name
                        .get(&mname)
                        .unwrap_or_else(|| panic!("unknown module {:?}", self.s(mname)));
                    // bind the child's parameters: its inputs align
                    // positionally with the instantiation args
                    let cmir = self.mods[cmod].ir;
                    let inputs: Vec<(StrId, ir::PortKind)> = self.d.modules[cmir]
                        .inputs
                        .iter()
                        .map(|p| (p.name, p.kind))
                        .collect();
                    let mut params = HashMap::new();
                    let mut str_params = HashMap::new();
                    let mut child_binds = HashMap::new();
                    let mut gate_binds = HashMap::new();
                    let mut clk_binds = HashMap::new();
                    // inputs align positionally with the instantiation
                    // args, except that a gated input clock occupies TWO
                    // input ports (Clock then ClockGate) bound from one
                    // Clock{osc,gate} arg
                    let mut pi = 0usize;
                    for arg in args.iter() {
                        if pi >= inputs.len() {
                            break;
                        }
                        let (pname_, kind_) = inputs[pi];
                        pi += 1;
                        match kind_ {
                            ir::PortKind::Clock => {
                                if let Expr::Clock { osc, .. } = arg {
                                    clk_binds.insert(
                                        pname_,
                                        (slot, osc.as_ref().clone()),
                                    );
                                }
                                if pi < inputs.len()
                                    && inputs[pi].1 == ir::PortKind::ClockGate
                                {
                                    let gname = inputs[pi].0;
                                    pi += 1;
                                    if let Expr::Clock { gate, .. } = arg {
                                        gate_binds.insert(
                                            gname,
                                            (slot, gate.as_ref().clone()),
                                        );
                                    }
                                }
                            }
                            ir::PortKind::ClockGate => {}
                            ir::PortKind::Reset => {
                                if let Expr::Reset { wire } = arg {
                                    if let Expr::Port(p) = wire.as_ref() {
                                        if let Some(&n) = reset_map.get(p) {
                                            child_binds.insert(pname_, n);
                                        }
                                    }
                                }
                            }
                            _ => match arg {
                                Expr::Str(sid) => {
                                    str_params.insert(pname_, *sid);
                                }
                                // a string parameter forwarded through an
                                // intermediate module level
                                Expr::Param(p) | Expr::Port(p)
                                    if self.str_param_of(slot, *p).is_some() =>
                                {
                                    let sid = self.str_param_of(slot, *p).unwrap();
                                    str_params.insert(pname_, sid);
                                }
                                _ => {
                                    let mut c = Ctx::default();
                                    let v = self.eval(slot, &mut c, arg);
                                    params.insert(pname_, v);
                                }
                            },
                        }
                    }
                    self.instantiate(
                        cpath.clone(),
                        cmod,
                        params,
                        str_params,
                        child_binds,
                        gate_binds,
                        clk_binds,
                    )
                }
                ir::InstanceKind::Prim(p) => {
                    let pname = match &p {
                        ir::Primitive::Other { name } => self.s(*name).to_string(),
                        other => panic!("structured primitive kinds not exported yet: {other:?}"),
                    };
                    // evaluate instantiation args in the parent context
                    // (they may reference the parent's own parameters);
                    // clocks/resets are connection info, not values
                    let mut consts: Vec<Value> = Vec::new();
                    let mut strs: Vec<String> = Vec::new();
                    for a in &args {
                        match a {
                            Expr::Clock { .. } | Expr::Reset { .. } | Expr::Gate { .. } => {}
                            Expr::Str(sid) => strs.push(self.s(*sid).to_string()),
                            Expr::Param(p) | Expr::Port(p)
                                if self.str_param_of(slot, *p).is_some() =>
                            {
                                let sid = self.str_param_of(slot, *p).unwrap();
                                strs.push(self.s(sid).to_string());
                            }
                            _ => {
                                let mut c = Ctx::default();
                                let v = self.eval(slot, &mut c, a);
                                // computed strings (e.g. StringConcat of
                                // parameters) are string args, not consts
                                match v.as_str_id() {
                                    Some(id) => strs.push(self.s(id).to_string()),
                                    None => consts.push(v),
                                }
                            }
                        }
                    }
                    if pname == "ClockGen" {
                        // args: v1Width, v2Width, initDelay, initValue,
                        // otherValue; high phase = initValue ? v2 : v1
                        let v1 = consts[0].as_u64();
                        let v2 = consts[1].as_u64();
                        let delay = consts[2].as_u64();
                        let init_high = consts[3].as_u64() != 0;
                        let (hi, lo) = if init_high { (v2, v1) } else { (v1, v2) };
                        self.clockgen_waves.insert(
                            format!("{cpath}$CLK_OUT"),
                            Wave { init_high, delay, hi, lo, has_init: true },
                        );
                    }
                    // dynamic clocks: record the initial output level; the
                    // driving prim instance is found again by path at run()
                    // (bk_enqueue_initial_clock_edge semantics)
                    match pname.as_str() {
                        "MakeClock" => {
                            let init_high = consts[0].as_u64() != 0;
                            self.dynclk_init
                                .insert(format!("{cpath}$CLK_OUT"), init_high);
                        }
                        "ClockDiv" => {
                            let width = consts[0].as_u64();
                            let upper = consts[2].as_u64();
                            let offset = consts[3].as_u64();
                            let init_high = (upper - offset) >= (1 << (width - 1));
                            self.dynclk_init
                                .insert(format!("{cpath}$CLK_OUT"), init_high);
                        }
                        "ClockInverter" | "GatedClockInverter" | "ClockMux"
                        | "UngatedClockMux" | "ClockSelect" | "UngatedClockSelect" => {
                            self.dynclk_init
                                .insert(format!("{cpath}$CLK_OUT"), false);
                        }
                        _ => {}
                    }
                    let idx = self.insts.len();
                    self.insts.push(Inst {
                        path: cpath.clone(),
                        kind: InstKind::Prim(prim::make_prim(&pname, &consts, &strs, &cpath)),
                    });
                    // reset-line subscriptions from Reset args wired to a
                    // live reset (a constant wire = noReset, never
                    // asserted); the ordinal distinguishes A_RST/B_RST on
                    // multi-input prims
                    let mut rst_ord = 0;
                    for a in &args {
                        if let Expr::Reset { wire } = a {
                            if let Expr::Port(p) = wire.as_ref() {
                                if let Some(&n) = reset_map.get(p) {
                                    self.rst_subs[n].push((idx, rst_ord));
                                }
                            }
                            rst_ord += 1;
                        }
                    }
                    // reset generators drive the node named <leaf>$OUT_RST
                    // in this module's reset list
                    if matches!(
                        pname.as_str(),
                        "SyncReset" | "SyncResetA" | "SyncReset0" | "InitialReset"
                            | "MakeReset" | "MakeResetA" | "MakeReset0"
                            | "ResetMux" | "ResetEither"
                            | "ClockSelect" | "UngatedClockSelect"
                    ) {
                        let t1 = format!("{}$OUT_RST", self.s(name));
                        let t2 = format!("{}$RST_OUT", self.s(name));
                        let out = reset_map
                            .iter()
                            .find(|(k, _)| self.s(**k) == t1 || self.s(**k) == t2)
                            .map(|(_, &n)| n);
                        if let Some(out) = out {
                            self.rstgen_out.insert(idx, out);
                            // InitialReset asserts its output from time 0
                            // (reset_init in set_reset_fn_gen_rst); the
                            // assert is broadcast at run() start once every
                            // subscriber exists
                            if pname == "InitialReset" {
                                self.initial_asserts.push(out);
                            }
                        }
                    }
                    self.inst_by_path.insert(cpath.clone(), idx);
                    idx
                }
            };
            if let InstKind::User { children, .. } = &mut self.insts[slot].kind {
                children.insert(name, cidx);
            }
        }
        slot
    }

    // ===============
    // Evaluation

    fn module_of(&self, inst: usize) -> usize {
        match &self.insts[inst].kind {
            InstKind::User { module, .. } => *module,
            InstKind::Prim(_) => panic!("primitive treated as user module"),
        }
    }

    fn child_of(&self, inst: usize, name: StrId) -> usize {
        match &self.insts[inst].kind {
            InstKind::User { children, .. } => *children
                .get(&name)
                .unwrap_or_else(|| panic!("unknown child instance {:?}", self.s(name))),
            InstKind::Prim(_) => panic!("primitive has no children"),
        }
    }

    fn latched(&self, inst: usize, name: StrId) -> Option<Value> {
        match &self.insts[inst].kind {
            InstKind::User { latched, .. } => latched.get(&name).cloned(),
            InstKind::Prim(_) => None,
        }
    }

    fn set_latched(&mut self, inst: usize, name: StrId, v: Value) {
        if let InstKind::User { latched, .. } = &mut self.insts[inst].kind {
            latched.insert(name, v);
        }
    }

    /// Evaluate an expression in an instance context.  Body-local defs and
    /// per-cycle latched defs win over recomputation; in memo contexts,
    /// on-demand def values are cached.
    fn eval(&mut self, inst: usize, ctx: &mut Ctx, e: &Expr) -> Value {
        match e {
            Expr::Const { width, limbs } => Value::from_limbs32(*width, limbs),
            Expr::Str(sid) => Value::str_ref(*sid),
            Expr::Def(name) => {
                if let Some(v) = ctx.locals.get(name) {
                    return v.clone();
                }
                if let Some(v) = self.latched(inst, *name) {
                    return v;
                }
                let module = self.module_of(inst);
                let mir = self.mods[module].ir;
                let di = *self.mods[module]
                    .defs
                    .get(name)
                    .unwrap_or_else(|| panic!("unknown def {:?}", self.s(*name)));
                let d = self.d.modules[mir].defs[di].clone();
                let v = self.eval(inst, ctx, &d.expr);
                if ctx.memo {
                    ctx.locals.insert(*name, v.clone());
                }
                v
            }
            Expr::Port(name) | Expr::Param(name) => {
                if let Some(v) = ctx.frame.get(name) {
                    return v.clone();
                }
                if let InstKind::User { params, str_params, .. } = &self.insts[inst].kind {
                    if let Some(v) = params.get(name) {
                        return v.clone();
                    }
                    // string parameters flow as marker values so dynamic
                    // muxes over them still resolve at task boundaries
                    if let Some(&sid) = str_params.get(name) {
                        return Value::str_ref(sid);
                    }
                }
                // module input ports outside a method frame: clock gates and
                // reset lines read as asserted-off (1); method enables and
                // args read as not-driven (0) — an uncalled method's EN must
                // be 0 or WILL_FIRE inhibitors derived from it (rule vs.
                // conflicting method, e.g. sysSchedFixTb's rm vs. step) would
                // suppress the rule every cycle
                if let InstKind::User { resets, .. } = &self.insts[inst].kind {
                    if let Some(&n) = resets.get(name) {
                        // active-low reset wire
                        return Value::from_u64(1, (!self.rst_asserted[n]) as u64);
                    }
                }
                // input clock-gate ports bound at instantiation resolve in
                // the parent instance (top-level input gates fall through
                // and read as constant 1, mirroring top_gates -> aTrue)
                if let InstKind::User { gates, .. } = &self.insts[inst].kind {
                    if let Some((owner, g)) = gates.get(name) {
                        let (owner, g) = (*owner, g.clone());
                        let mut c = Ctx::default();
                        return self.eval(owner, &mut c, &g);
                    }
                }
                // flattened gate wires of derived clocks: the exporter
                // writes "<absolute.path>$CLK_GATE_OUT" for qualified
                // gate ports (tick gates); module-local Gate reads come
                // through Expr::Gate instead
                if let Some(path) = self.s(*name).strip_suffix("$CLK_GATE_OUT") {
                    let candidates = [path.to_string(), {
                        let base = &self.insts[inst].path;
                        if base.is_empty() {
                            path.to_string()
                        } else {
                            format!("{base}.{path}")
                        }
                    }];
                    for p in &candidates {
                        if let Some(&ci) = self.inst_by_path.get(p) {
                            if let InstKind::Prim(pr) = &self.insts[ci].kind {
                                return Value::from_u64(1, pr.gate_out() as u64);
                            }
                        }
                    }
                }
                let module = self.module_of(inst);
                match self.mods[module].ports.get(name) {
                    // EN_* is latched 1 for the rest of the pass when the
                    // method executes (urgency inhibitors read it); an
                    // uncalled method's EN reads 0
                    Some(&(w, ir::PortKind::MethodEnable)) => self
                        .latched(inst, *name)
                        .unwrap_or_else(|| Value::from_u64(w, 0)),
                    Some(&(w, ir::PortKind::MethodArg)) => Value::from_u64(w, 0),
                    Some(&(w, _)) => Value::from_u64(w, 1),
                    None => Value::from_u64(1, 1),
                }
            }
            Expr::MethCall { width, instance, method, args, .. } => {
                let argv: Vec<Value> =
                    args.iter().map(|a| self.eval(inst, ctx, a)).collect();
                let child = self.child_of(inst, *instance);
                self.call_value(child, *method, &argv, *width)
            }
            Expr::MethValue { width, instance, method } => {
                let child = self.child_of(inst, *instance);
                self.call_value(child, *method, &[], *width)
            }
            Expr::TaskValue { width, cookie } => {
                // value produced by the paired Task action earlier in this
                // body, stored under a synthetic key
                ctx.locals
                    .get(&cookie_key(*cookie))
                    .cloned()
                    .or_else(|| self.latched(inst, cookie_key(*cookie)))
                    .unwrap_or_else(|| Value::undet(*width))
            }
            Expr::ForeignCall { width, func, args } => {
                let fname = self.s(*func).to_string();
                let argv: Vec<Arg> = args
                    .iter()
                    .map(|a| self.eval_arg(inst, ctx, a, false))
                    .collect();
                let loc = self.loc_of(inst);
                self.foreign_value(&fname, &argv, *width, &loc)
            }
            Expr::Gate { instance, .. } => {
                let child = self.child_of(inst, *instance);
                match &self.insts[child].kind {
                    InstKind::Prim(p) => Value::from_u64(1, p.gate_out() as u64),
                    // a user module's exported gate: not modeled yet
                    _ => Value::from_u64(1, 1),
                }
            }
            Expr::Clock { .. } => Value::from_u64(1, 1),
            Expr::Reset { wire } => self.eval(inst, ctx, wire),
            Expr::Real(r) => Value::real(*r),
            Expr::Prim { op, width, args } => self.eval_prim(inst, ctx, *op, *width, args),
            Expr::If { width, cond, then_, else_ } => {
                if self.eval(inst, ctx, cond).as_bool() {
                    self.eval(inst, ctx, then_).zext(*width)
                } else {
                    self.eval(inst, ctx, else_).zext(*width)
                }
            }
            Expr::Case { width, scrutinee, arms, default } => {
                let s = self.eval(inst, ctx, scrutinee);
                for (k, v) in arms {
                    if s.as_u64() == *k && s.width <= 64 {
                        return self.eval(inst, ctx, v).zext(*width);
                    }
                }
                self.eval(inst, ctx, default).zext(*width)
            }
        }
    }

    fn eval_prim(
        &mut self,
        inst: usize,
        ctx: &mut Ctx,
        op: PrimOp,
        w: u32,
        args: &[Expr],
    ) -> Value {
        match op {
            // And/Or/Xor/Add/Mul are associative and may appear n-ary in ASyntax.
            PrimOp::And => {
                let mut acc = self.eval(inst, ctx, &args[0]);
                for a in &args[1..] {
                    let b = self.eval(inst, ctx, a);
                    acc = acc.and(&b, w);
                }
                acc
            }
            PrimOp::Or => {
                let mut acc = self.eval(inst, ctx, &args[0]);
                for a in &args[1..] {
                    let b = self.eval(inst, ctx, a);
                    acc = acc.or(&b, w);
                }
                acc
            }
            PrimOp::Xor => {
                let mut acc = self.eval(inst, ctx, &args[0]);
                for a in &args[1..] {
                    let b = self.eval(inst, ctx, a);
                    acc = acc.xor(&b, w);
                }
                acc
            }
            PrimOp::Not => self.eval(inst, ctx, &args[0]).not(w),
            PrimOp::Add => {
                let mut acc = self.eval(inst, ctx, &args[0]);
                for a in &args[1..] {
                    let b = self.eval(inst, ctx, a);
                    acc = acc.add(&b, w);
                }
                acc
            }
            PrimOp::Sub => {
                let a = self.eval(inst, ctx, &args[0]);
                let b = self.eval(inst, ctx, &args[1]);
                a.sub(&b, w)
            }
            PrimOp::Neg => self.eval(inst, ctx, &args[0]).neg(w),
            PrimOp::Mul => {
                let mut acc = self.eval(inst, ctx, &args[0]);
                for a in &args[1..] {
                    let b = self.eval(inst, ctx, a);
                    acc = acc.mul(&b, w);
                }
                acc
            }
            PrimOp::Quot => {
                let a = self.eval(inst, ctx, &args[0]);
                let b = self.eval(inst, ctx, &args[1]);
                a.quot(&b, w)
            }
            PrimOp::Rem => {
                let a = self.eval(inst, ctx, &args[0]);
                let b = self.eval(inst, ctx, &args[1]);
                a.rem(&b, w)
            }
            PrimOp::Eq => {
                let a = self.eval(inst, ctx, &args[0]);
                let b = self.eval(inst, ctx, &args[1]);
                Value::from_u64(1, a.eq(&b) as u64)
            }
            PrimOp::Ult => {
                let a = self.eval(inst, ctx, &args[0]);
                let b = self.eval(inst, ctx, &args[1]);
                Value::from_u64(1, a.ult(&b) as u64)
            }
            PrimOp::Ule => {
                let a = self.eval(inst, ctx, &args[0]);
                let b = self.eval(inst, ctx, &args[1]);
                Value::from_u64(1, a.ule(&b) as u64)
            }
            PrimOp::Slt => {
                let a = self.eval(inst, ctx, &args[0]);
                let b = self.eval(inst, ctx, &args[1]);
                Value::from_u64(1, a.slt(&b) as u64)
            }
            PrimOp::Sle => {
                let a = self.eval(inst, ctx, &args[0]);
                let b = self.eval(inst, ctx, &args[1]);
                Value::from_u64(1, a.sle(&b) as u64)
            }
            PrimOp::Shl => {
                let a = self.eval(inst, ctx, &args[0]);
                let sh = self.eval(inst, ctx, &args[1]).as_u64();
                a.shl(sh, w)
            }
            PrimOp::Lshr => {
                let a = self.eval(inst, ctx, &args[0]);
                let sh = self.eval(inst, ctx, &args[1]).as_u64();
                a.lshr(sh, w)
            }
            PrimOp::Ashr => {
                let a = self.eval(inst, ctx, &args[0]);
                let sh = self.eval(inst, ctx, &args[1]).as_u64();
                a.ashr(sh, w)
            }
            PrimOp::Extract => {
                // PrimExtract e hi lo
                let a = self.eval(inst, ctx, &args[0]);
                let hi = self.eval(inst, ctx, &args[1]).as_u64();
                let lo = self.eval(inst, ctx, &args[2]).as_u64();
                a.extract(hi, lo, w)
            }
            PrimOp::Concat => {
                // left-to-right, first is most significant
                let mut acc = self.eval(inst, ctx, &args[0]);
                let mut accw = acc.width;
                for k in 1..args.len() {
                    let nxt = self.eval(inst, ctx, &args[k]);
                    accw += nxt.width;
                    acc = acc.concat(&nxt, accw);
                }
                acc.zext(w)
            }
            PrimOp::ZeroExt => self.eval(inst, ctx, &args[0]).zext(w),
            PrimOp::SignExt => self.eval(inst, ctx, &args[0]).sext(w),
            PrimOp::Select => {
                panic!("PrimArrayDynSelect should be expanded by simPackageOpt")
            }
            PrimOp::StringConcat => {
                let mut text = String::new();
                for a in args {
                    let v = self.eval(inst, ctx, a);
                    match v.as_str_id() {
                        Some(id) => text.push_str(self.s(id)),
                        None => panic!("StringConcat of a non-string value"),
                    }
                }
                let id = self.intern_dyn(text);
                Value::str_ref(id)
            }
        }
    }

    fn eval_arg(&mut self, inst: usize, ctx: &mut Ctx, e: &Expr, signed: bool) -> Arg {
        match e {
            Expr::Str(s) => Arg::Str(self.s(*s).to_string()),
            Expr::Port(name) | Expr::Param(name) => {
                if let InstKind::User { str_params, .. } = &self.insts[inst].kind {
                    if let Some(&sid) = str_params.get(name) {
                        return Arg::Str(self.s(sid).to_string());
                    }
                }
                let v = self.eval(inst, ctx, e);
                self.val_arg(v, signed)
            }
            _ => {
                let v = self.eval(inst, ctx, e);
                self.val_arg(v, signed)
            }
        }
    }

    /// Dynamically selected strings and reals surface as marker values.
    fn val_arg(&self, v: Value, signed: bool) -> Arg {
        if let Some(r) = v.as_real() {
            return Arg::Real(r);
        }
        match v.as_str_id() {
            Some(id) => Arg::Str(self.s(id).to_string()),
            None => Arg::Val(v, signed),
        }
    }

    // ===============
    // Method calls

    fn method_ctx(&mut self, callee_mod: usize, mi: usize, argv: &[Value], memo: bool) -> Ctx {
        let mir = self.mods[callee_mod].ir;
        let m = &self.d.modules[mir].methods[mi];
        Ctx {
            frame: m.args.iter().zip(argv.iter()).map(|(p, v)| (p.name, v.clone())).collect(),
            locals: HashMap::new(),
            memo,
        }
    }

    fn call_value(&mut self, callee: usize, method: StrId, argv: &[Value], w: u32) -> Value {
        match &mut self.insts[callee].kind {
            InstKind::Prim(p) => {
                let mname = self.d.strings[method as usize].clone();
                let r = p.value_method(&mname, argv, self.now);
                if std::env::var_os("TRS_TRACE").is_some() {
                    let path = self.insts[callee].path.clone();
                    eprintln!("[{}] {}.{} -> {}", self.cycle, path, mname,
                              r.to_hex_string());
                }
                return r;
            }
            InstKind::User { module, .. } => {
                let module = *module;
                let mi = *self.mods[module]
                    .methods
                    .get(&method)
                    .unwrap_or_else(|| panic!("unknown method {:?}", self.s(method)));
                let mir = self.mods[module].ir;
                let result = self.d.modules[mir].methods[mi].result.clone();
                let mut ctx = self.method_ctx(module, mi, argv, true);
                match result {
                    Some(r) => self.eval(callee, &mut ctx, &r).zext(w),
                    None => panic!("value call to method without result"),
                }
            }
        }
    }

    fn call_action(&mut self, callee: usize, method: StrId, argv: &[Value]) {
        if std::env::var_os("TRS_TRACE").is_some() {
            if let InstKind::Prim(_) = &self.insts[callee].kind {
                let mname = self.d.strings[method as usize].clone();
                let args: Vec<String> = argv.iter().map(|v| v.to_hex_string()).collect();
                eprintln!("[{}] {}.{}({})", self.cycle, self.insts[callee].path,
                          mname, args.join(","));
            }
        }
        match &mut self.insts[callee].kind {
            InstKind::Prim(p) => {
                let mname = self.d.strings[method as usize].clone();
                p.action_method(&mname, argv, self.now);
            }
            InstKind::User { module, .. } => {
                let module = *module;
                let mi = *self.mods[module]
                    .methods
                    .get(&method)
                    .unwrap_or_else(|| panic!("unknown method {:?}", self.s(method)));
                self.latch_method_en(callee, method);
                let mir = self.mods[module].ir;
                let body: Vec<Stmt> = self.d.modules[mir].methods[mi].body.clone();
                let mut ctx = self.method_ctx(module, mi, argv, false);
                for st in &body {
                    self.exec_stmt(callee, &mut ctx, st);
                }
            }
        }
    }

    /// Record that an action/actionvalue method fired this pass: the C++
    /// schedule zeroes every EN_* at the top of the pass and sets it when
    /// the method executes, and WILL_FIRE urgency inhibitors of
    /// conflicting rules read it later in the same pass.
    fn latch_method_en(&mut self, callee: usize, method: StrId) {
        let en = format!("EN_{}", self.s(method));
        if let Some(en_id) = self.d.strings.iter().position(|x| x == &en) {
            if let InstKind::User { latched, .. } = &mut self.insts[callee].kind {
                latched.insert(en_id as StrId, Value::from_u64(1, 1));
            }
        }
    }

    fn call_actionvalue(&mut self, callee: usize, method: StrId, argv: &[Value]) -> Value {
        match &mut self.insts[callee].kind {
            InstKind::Prim(p) => {
                let mname = self.d.strings[method as usize].clone();
                p.actionvalue_method(&mname, argv, self.now)
            }
            InstKind::User { module, .. } => {
                let module = *module;
                let mi = *self.mods[module]
                    .methods
                    .get(&method)
                    .unwrap_or_else(|| panic!("unknown method {:?}", self.s(method)));
                self.latch_method_en(callee, method);
                let mir = self.mods[module].ir;
                let body: Vec<Stmt> = self.d.modules[mir].methods[mi].body.clone();
                let result = self.d.modules[mir].methods[mi].result.clone();
                let mut ctx = self.method_ctx(module, mi, argv, false);
                for st in &body {
                    self.exec_stmt(callee, &mut ctx, st);
                }
                match result {
                    Some(r) => {
                        if std::env::var_os("TRS_TRACE").is_some() {
                            eprintln!("    av-result expr: {r:?}");
                        }
                        self.eval(callee, &mut ctx, &r)
                    }
                    None => panic!("actionvalue method without result"),
                }
            }
        }
    }

    // ===============
    // Statements and actions

    /// Execute one body statement: defs are computed at their exact
    /// position (a later action must not affect them).
    fn exec_stmt(&mut self, inst: usize, ctx: &mut Ctx, st: &Stmt) {
        if self.finished.is_some() {
            return;
        }
        match st {
            Stmt::Def { name, expr } => {
                let v = self.eval(inst, ctx, expr);
                if std::env::var_os("TRS_TRACE").is_some() {
                    eprintln!("    def {} := {}", self.s(*name), v.to_hex_string());
                }
                ctx.locals.insert(*name, v);
            }
            Stmt::Action(a) => self.exec_action(inst, ctx, a),
            Stmt::AvAction { def, action } => match action {
                Action::MethCall { instance, method, cond, args, .. } => {
                    if !self.eval(inst, ctx, cond).as_bool() {
                        let dw = self.def_width(inst, *def).unwrap_or(1);
                        ctx.locals.insert(*def, Value::undet(dw));
                        return;
                    }
                    let argv: Vec<Value> =
                        args.iter().map(|x| self.eval(inst, ctx, x)).collect();
                    let child = self.child_of(inst, *instance);
                    let v = self.call_actionvalue(child, *method, &argv);
                    // synthetic AV temps are not in the def table; the
                    // callee's result already has the declared width
                    let v = match self.def_width(inst, *def) {
                        Some(dw) => v.zext(dw),
                        None => v,
                    };
                    ctx.locals.insert(*def, v);
                }
                a @ Action::Task { temp, width, .. } => {
                    self.exec_action(inst, ctx, a);
                    let v = temp
                        .and_then(|t| ctx.locals.get(&t).cloned())
                        .unwrap_or_else(|| Value::undet((*width).max(1)));
                    ctx.locals.insert(*def, v);
                }
                other => panic!("AvAction with non-method action: {other:?}"),
            },
            Stmt::Cond { cond, then_, else_ } => {
                let branch = if self.eval(inst, ctx, cond).as_bool() {
                    then_
                } else {
                    else_
                };
                for st in branch.clone() {
                    self.exec_stmt(inst, ctx, &st);
                }
            }
        }
    }

    fn def_width(&self, inst: usize, name: StrId) -> Option<u32> {
        let module = self.module_of(inst);
        let mir = self.mods[module].ir;
        self.mods[module]
            .defs
            .get(&name)
            .map(|di| self.d.modules[mir].defs[*di].width)
    }

    fn exec_action(&mut self, inst: usize, ctx: &mut Ctx, a: &Action) {
        if self.finished.is_some() {
            return;
        }
        match a {
            Action::MethCall { instance, method, cond, args, .. } => {
                if !self.eval(inst, ctx, cond).as_bool() {
                    return;
                }
                let argv: Vec<Value> =
                    args.iter().map(|x| self.eval(inst, ctx, x)).collect();
                let child = self.child_of(inst, *instance);
                self.call_action(child, *method, &argv);
            }
            Action::Foreign { func, cond, args, signed } => {
                if !self.eval(inst, ctx, cond).as_bool() {
                    return;
                }
                let fname = self.s(*func).to_string();
                let argv: Vec<Arg> = args
                    .iter()
                    .zip(signed.iter().chain(std::iter::repeat(&false)))
                    .map(|(x, sg)| self.eval_arg(inst, ctx, x, *sg))
                    .collect();
                let loc = self.loc_of(inst);
                self.foreign_action(&fname, &argv, &loc);
            }
            Action::Task { func, cookie, temp, width, cond, args, signed } => {
                if !self.eval(inst, ctx, cond).as_bool() {
                    return;
                }
                let fname = self.s(*func).to_string();
                let argv: Vec<Arg> = args
                    .iter()
                    .zip(signed.iter().chain(std::iter::repeat(&false)))
                    .map(|(x, sg)| self.eval_arg(inst, ctx, x, *sg))
                    .collect();
                let loc = self.loc_of(inst);
                let v = self.foreign_value(&fname, &argv, *width, &loc);
                ctx.locals.insert(cookie_key(*cookie), v.clone());
                if let Some(t) = temp {
                    ctx.locals.insert(*t, v);
                }
            }
        }
    }

    // ===============
    // System tasks

    /// Write to every channel a file key names (VLFiles::findFiles): keys
    /// with bit 31 index the fd table; smaller keys are MCD bitmasks
    /// fanning out to each set bit (bit 0 = stdout).
    fn write_fd(&mut self, key: u64, text: &str) {
        use std::io::Write;
        let write_slot = |s: &mut FSlot| match s {
            FSlot::Stdout => print!("{text}"),
            FSlot::Stderr => eprint!("{text}"),
            FSlot::File(f) => {
                let _ = f.write_all(text.as_bytes());
            }
            _ => {}
        };
        if key >= 0x8000_0000 {
            let idx = (key - 0x8000_0000) as usize;
            if let Some(s) = self.fd_files.get_mut(idx) {
                write_slot(s);
            }
        } else {
            let mut k = key;
            let mut i = 0usize;
            while k != 0 {
                if k & 1 == 1 {
                    if let Some(s) = self.mcd_files.get_mut(i) {
                        write_slot(s);
                    }
                }
                k >>= 1;
                i += 1;
            }
        }
    }

    /// VLFiles::closeFiles: fd keys above the std handles close their
    /// slot; MCD masks close every set bit except stdout (bit 0).
    fn close_files(&mut self, key: u64) {
        if key > 0x8000_0002 {
            let idx = (key - 0x8000_0000) as usize;
            if let Some(s) = self.fd_files.get_mut(idx) {
                if matches!(s, FSlot::File(_)) {
                    *s = FSlot::Closed;
                }
            }
        } else if key < 0x0800_0000 {
            let mut k = key >> 1; // skip stdout
            let mut i = 1usize;
            while k != 0 {
                if k & 1 == 1 {
                    if let Some(s) = self.mcd_files.get_mut(i) {
                        if matches!(s, FSlot::File(_)) {
                            *s = FSlot::Closed;
                        }
                    }
                }
                k >>= 1;
                i += 1;
            }
        }
    }

    /// dlopen the companion BDPI shared object and resolve the design's
    /// imported functions.
    pub fn load_bdpi(&mut self, path: &str) -> Result<(), String> {
        let funcs: Vec<(String, String)> = self
            .d
            .foreign_funcs
            .iter()
            .map(|f| (self.s(f.name).to_string(), self.s(f.c_name).to_string()))
            .collect();
        self.bdpi = Some(bdpi::Bdpi::load(std::path::Path::new(path), &funcs)?);
        Ok(())
    }

    /// Dispatch a non-builtin task name as a BDPI import, if the design
    /// declares one.
    fn bdpi_call(&mut self, name: &str, args: &[Arg], w: u32) -> Option<Value> {
        let ff = self
            .d
            .foreign_funcs
            .iter()
            .find(|f| self.s(f.name) == name)?
            .clone();
        let b = self.bdpi.as_ref().unwrap_or_else(|| {
            panic!(
                "BDPI function {name:?} called but no .bdpi.so was found \
                 next to the .bir (link with the user's C files)"
            )
        });
        Some(b.call(&ff, name, args, w))
    }

    /// %m location string: the hierarchical name of the module executing
    /// the task (the C++ passes `this` and write_name prints it).
    fn loc_of(&self, inst: usize) -> String {
        let p = &self.insts[inst].path;
        if p.is_empty() {
            "top".to_string()
        } else {
            format!("top.{p}")
        }
    }

    fn foreign_action(&mut self, name: &str, args: &[Arg], loc: &str) {
        match name {
            "$fdisplay" | "$fwrite" | "$fdisplayh" | "$fwriteh"
            | "$fdisplayb" | "$fwriteb" | "$fdisplayo" | "$fwriteo" => {
                let base = match name.chars().last() {
                    Some('h') => 16,
                    Some('b') => 2,
                    Some('o') => 8,
                    _ => 10,
                };
                let fd = match args.first() {
                    Some(Arg::Val(v, _)) => v.as_u64(),
                    _ => 0x8000_0000,
                };
                let mut errs = Vec::new();
                let mut text =
                    format::format_args(&args[1..], base, self.now, loc, &mut errs);
                if name.starts_with("$fdisplay") {
                    text.push('\n');
                }
                self.write_fd(fd, &text);
                emit_output_errors(&errs);
            }
            "$fclose" => {
                if let Some(Arg::Val(v, _)) = args.first() {
                    self.close_files(v.as_u64());
                }
            }
            "$fflush" => {
                use std::io::Write;
                let _ = std::io::stdout().flush();
                let key = match args.first() {
                    Some(Arg::Val(v, _)) => Some(v.as_u64()),
                    _ => None,
                };
                for tbl in [&mut self.fd_files, &mut self.mcd_files] {
                    for s in tbl.iter_mut() {
                        if let FSlot::File(f) = s {
                            if key.is_none() {
                                let _ = f.flush();
                            }
                        }
                    }
                }
                if let Some(k) = key {
                    // flush the key's fan-out by writing nothing through
                    // the same decode path, then flushing each file
                    if k >= 0x8000_0000 {
                        if let Some(FSlot::File(f)) =
                            self.fd_files.get_mut((k - 0x8000_0000) as usize)
                        {
                            let _ = f.flush();
                        }
                    } else {
                        let (mut kk, mut i) = (k, 0usize);
                        while kk != 0 {
                            if kk & 1 == 1 {
                                if let Some(FSlot::File(f)) = self.mcd_files.get_mut(i) {
                                    let _ = f.flush();
                                }
                            }
                            kk >>= 1;
                            i += 1;
                        }
                    }
                }
            }
            "$display" => {
                let mut errs = Vec::new();
                println!("{}", format::format_args(args, 10, self.now, loc, &mut errs));
                emit_output_errors(&errs);
            }
            "$displayh" => {
                let mut errs = Vec::new();
                println!("{}", format::format_args(args, 16, self.now, loc, &mut errs));
                emit_output_errors(&errs);
            }
            "$displayb" => {
                let mut errs = Vec::new();
                println!("{}", format::format_args(args, 2, self.now, loc, &mut errs));
                emit_output_errors(&errs);
            }
            "$displayo" => {
                let mut errs = Vec::new();
                println!("{}", format::format_args(args, 8, self.now, loc, &mut errs));
                emit_output_errors(&errs);
            }
            "$write" => {
                let mut errs = Vec::new();
                print!("{}", format::format_args(args, 10, self.now, loc, &mut errs));
                emit_output_errors(&errs);
            }
            "$writeh" => {
                let mut errs = Vec::new();
                print!("{}", format::format_args(args, 16, self.now, loc, &mut errs));
                emit_output_errors(&errs);
            }
            "$writeb" => {
                let mut errs = Vec::new();
                print!("{}", format::format_args(args, 2, self.now, loc, &mut errs));
                emit_output_errors(&errs);
            }
            "$writeo" => {
                let mut errs = Vec::new();
                print!("{}", format::format_args(args, 8, self.now, loc, &mut errs));
                emit_output_errors(&errs);
            }
            // dollar_error/dollar_warning/dollar_info format exactly like
            // $display — bsc compiles the severity prefix into the message
            "$error" | "$warning" | "$info" => {
                let mut errs = Vec::new();
                println!("{}", format::format_args(args, 10, self.now, loc, &mut errs));
                emit_output_errors(&errs);
            }
            "$fatal" => {
                // first argument is the status passed to bk_fatal_now; the
                // driver ignores it and exits 1 whenever $fatal fired
                let rest = match args.split_first() {
                    Some((Arg::Val(_, _), rest)) => rest,
                    _ => args,
                };
                let mut errs = Vec::new();
                println!("{}", format::format_args(rest, 10, self.now, loc, &mut errs));
                emit_output_errors(&errs);
                self.fataled = true;
                self.finished = Some(1);
            }
            "$finish" => {
                let code = match args.first() {
                    Some(Arg::Val(v, _)) => v.as_u64() as i32,
                    _ => 0,
                };
                self.finished = Some(code);
            }
            "$stop" => self.finished = Some(0),
            "$dumpvars" | "$dumpon" | "$dumpoff" | "$dumpfile" | "$dumpall"
            | "$dumplimit" | "$dumpflush" => {} // waves: P2
            other => {
                if self.bdpi_call(other, args, 1).is_none() {
                    panic!("trs-interp: unimplemented system task {other:?}");
                }
            }
        }
    }

    fn foreign_value(&mut self, name: &str, args: &[Arg], w: u32, loc: &str) -> Value {
        match name {
            "$time" | "$stime" => Value::from_u64(w.max(1), self.now),
            "$fopen" => {
                let path = match args.first() {
                    Some(Arg::Str(s)) => s.clone(),
                    _ => return Value::zero(w.max(1)),
                };
                // one-arg form = MCD (always write mode); two-arg = fd
                let mcd = !matches!(args.get(1), Some(Arg::Str(_)));
                let write_mode = !matches!(args.get(1), Some(Arg::Str(m)) if m.starts_with('r'));
                let f = if write_mode {
                    std::fs::File::create(&path)
                } else {
                    std::fs::File::open(&path)
                };
                match f {
                    Ok(f) => {
                        let key = if mcd {
                            // registerFile(true,..): append below 31 bits,
                            // else reuse a closed slot
                            if self.mcd_files.len() < 31 {
                                self.mcd_files.push(FSlot::File(f));
                                1u64 << (self.mcd_files.len() - 1)
                            } else if let Some(i) = self
                                .mcd_files
                                .iter()
                                .position(|s| matches!(s, FSlot::Closed))
                            {
                                self.mcd_files[i] = FSlot::File(f);
                                1u64 << i
                            } else {
                                return Value::zero(w.max(1));
                            }
                        } else {
                            self.fd_files.push(FSlot::File(f));
                            0x8000_0000 + (self.fd_files.len() as u64 - 1)
                        };
                        Value::from_u64(w.max(32), key)
                    }
                    Err(_) => Value::zero(w.max(1)),
                }
            }
            // prefix match against the registered +args (bk_match_argument)
            "$test$plusargs" => {
                let name = match args.first() {
                    Some(Arg::Str(s)) => s.clone(),
                    Some(Arg::Val(v, _)) => format::unpack_str_pub(v),
                    _ => String::new(),
                };
                let hit = self.plusargs.iter().any(|a| a.starts_with(&name));
                Value::from_u64(w.max(1), hit as u64)
            }
            "$fgetc" => {
                use std::io::Read;
                let fd = match args.first() {
                    Some(Arg::Val(v, _)) => v.as_u64(),
                    _ => return Value::from_u64(w.max(32), u32::MAX as u64),
                };
                if let Some(b) = self.pushback.get_mut(&fd).and_then(|s| s.pop()) {
                    return Value::from_u64(w.max(32), b as u64);
                }
                // getFD: the fd table only
                let mut byte = [0u8; 1];
                if fd >= 0x8000_0000 {
                    match self.fd_files.get_mut((fd - 0x8000_0000) as usize) {
                        Some(FSlot::File(f)) => {
                            if f.read_exact(&mut byte).is_ok() {
                                return Value::from_u64(w.max(32), byte[0] as u64);
                            }
                        }
                        Some(FSlot::Stdin) => {
                            if std::io::stdin().read_exact(&mut byte).is_ok() {
                                return Value::from_u64(w.max(32), byte[0] as u64);
                            }
                        }
                        _ => {}
                    }
                }
                // EOF / bad fd: -1
                Value::from_u64(w.max(32), 0xFFFF_FFFF)
            }
            "$ungetc" => {
                // args: (char, fd); pushes back for the next $fgetc and
                // returns the char (C ungetc semantics)
                let c = match args.first() {
                    Some(Arg::Val(v, _)) => v.as_u64() as u8,
                    _ => 0,
                };
                let fd = match args.get(1) {
                    Some(Arg::Val(v, _)) => v.as_u64(),
                    _ => 0,
                };
                // valid on any live fd-table entry (getFD != NULL)
                let live = fd >= 0x8000_0000
                    && !matches!(
                        self.fd_files.get((fd - 0x8000_0000) as usize),
                        None | Some(FSlot::Closed)
                    );
                if live {
                    self.pushback.entry(fd).or_default().push(c);
                    Value::from_u64(w.max(32), c as u64)
                } else {
                    Value::from_u64(w.max(32), 0xFFFF_FFFF)
                }
            }
            "$swriteAV" | "$sformatAV" | "$swritebAV" | "$swriteoAV" | "$swritehAV" => {
                // format into a string, then pack the ASCII bytes into the
                // result width (right-justified, like the C++ BufferTarget
                // + copy_back)
                let base = match name {
                    "$swritebAV" => 2,
                    "$swriteoAV" => 8,
                    "$swritehAV" => 16,
                    _ => 10,
                };
                let mut errs = Vec::new();
                let text = format::format_sformat(
                    args, base, self.now, loc, name == "$sformatAV", &mut errs,
                );
                emit_output_errors(&errs);
                let packed = format::str_value(&text);
                if packed.width >= w {
                    packed.extract(w as u64 - 1, 0, w)
                } else {
                    packed.zext(w)
                }
            }
            "$fclose" => {
                if let Some(Arg::Val(v, _)) = args.first() {
                    self.close_files(v.as_u64());
                }
                Value::zero(w.max(1))
            }
            other => match self.bdpi_call(other, args, w) {
                Some(v) => v.zext(w.max(1)),
                None => {
                    panic!("trs-interp: unimplemented value task {other:?} ({args:?})")
                }
            },
        }
    }

    // ===============
    // Cycle execution

    fn latch_rule(&mut self, inst: usize, rule_name: StrId, cross_inh: &[(usize, StrId)]) {
        let module = self.module_of(inst);
        let mir = self.mods[module].ir;
        let ri = match self.mods[module].rules.get(&rule_name) {
            Some(ri) => *ri,
            None => return, // method node in a segment: nothing to latch
        };
        let r = self.d.modules[mir].rules[ri].clone();
        let mut ctx = Ctx { memo: true, ..Default::default() };

        let mut cf = self.eval(inst, &mut ctx, &Expr::Def(r.can_fire));
        // intra-module ME inhibitors (earlier disjoint rules' CFs)
        for other in &r.me_inhibits {
            let other_ri = self.mods[module].rules[other];
            let other_cf = self.d.modules[mir].rules[other_ri].can_fire;
            if let Some(v) = self.latched(inst, other_cf) {
                if v.as_bool() {
                    cf = Value::zero(1);
                }
            }
        }
        // cross-module inhibitors targeting this rule
        for (other_inst, other_cf) in cross_inh {
            if let Some(v) = self.latched(*other_inst, *other_cf) {
                if v.as_bool() {
                    cf = Value::zero(1);
                }
            }
        }
        self.set_latched(inst, r.can_fire, cf);
        // recompute the WILL_FIRE cone against the (possibly inhibited)
        // latched CAN_FIRE, not the memoized pre-inhibitor values
        let mut wf_ctx = Ctx { memo: true, ..Default::default() };
        let wf = self.eval(inst, &mut wf_ctx, &Expr::Def(r.will_fire));
        if std::env::var_os("TRS_TRACE_WF").is_some() && wf.as_bool() {
            eprintln!("[{}] FIRE {}.{}", self.cycle, self.insts[inst].path,
                      self.s(rule_name));
        }
        self.set_latched(inst, r.will_fire, wf);
    }

    fn exec_rule(&mut self, inst: usize, rule_name: StrId) {
        let module = self.module_of(inst);
        let mir = self.mods[module].ir;
        let ri = match self.mods[module].rules.get(&rule_name) {
            Some(ri) => *ri,
            None => return,
        };
        let r = self.d.modules[mir].rules[ri].clone();
        let fire = self
            .latched(inst, r.will_fire)
            .map(|v| v.as_bool())
            .unwrap_or(false);
        if !fire {
            return;
        }
        let mut ctx = Ctx::default();
        for st in &r.body {
            self.exec_stmt(inst, &mut ctx, st);
        }
    }

    /// Apply a reset-node transition: broadcast to subscribed prims, then
    /// poll reset generators among them — asynchronous assertion cascades
    /// immediately (reset_fn called inside reset_IN_RST), synchronous /
    /// deassert transitions defer to the end of the timeslice
    /// (reset_at_end_of_timeslice).
    fn apply_reset(&mut self, node: usize, asserted: bool) {
        let mut work = vec![(node, asserted)];
        while let Some((n, v)) = work.pop() {
            if self.rst_asserted[n] == v {
                continue;
            }
            self.rst_asserted[n] = v;
            let subs = self.rst_subs[n].clone();
            for (idx, ord) in subs {
                if let InstKind::Prim(p) = &mut self.insts[idx].kind {
                    p.set_reset_input(ord, v);
                    if self.rstgen_out.contains_key(&idx) {
                        for (out_v, immediate) in p.take_reset_out() {
                            let out = self.rstgen_out[&idx];
                            if immediate {
                                work.push((out, out_v));
                            } else {
                                self.rst_pending.push((out, out_v));
                            }
                        }
                    }
                }
            }
        }
    }

    /// Poll one reset generator after its clock tick and route its
    /// pending output transitions.
    fn poll_rstgen(&mut self, idx: usize) {
        let Some(&out) = self.rstgen_out.get(&idx) else { return };
        let outs = if let InstKind::Prim(p) = &mut self.insts[idx].kind {
            p.take_reset_out()
        } else {
            return;
        };
        for (v, immediate) in outs {
            if immediate {
                self.apply_reset(out, v);
            } else {
                self.rst_pending.push((out, v));
            }
        }
    }

    /// End of timeslice: let generators move internally deferred
    /// transitions forward, then apply all deferred transitions (which
    /// may cascade into more, applied in the same instant).
    fn flush_reset_pending(&mut self) {
        let gens: Vec<usize> = self.rstgen_out.keys().copied().collect();
        for idx in gens {
            if let InstKind::Prim(p) = &mut self.insts[idx].kind {
                p.end_of_timeslice();
            }
            self.poll_rstgen_deferred(idx);
        }
        while let Some((n, v)) = self.rst_pending.pop() {
            self.apply_reset(n, v);
        }
    }

    /// Poll a generator, treating everything as applicable now (used at
    /// flush time, when deferred == immediate).
    fn poll_rstgen_deferred(&mut self, idx: usize) {
        let Some(&out) = self.rstgen_out.get(&idx) else { return };
        let outs = if let InstKind::Prim(p) = &mut self.insts[idx].kind {
            p.take_reset_out()
        } else {
            return;
        };
        for (v, _) in outs {
            self.rst_pending.push((out, v));
        }
    }

    fn default_wave() -> ClockSource {
        ClockSource::Wave(Wave { init_high: false, delay: 0, hi: 5, lo: 5, has_init: false })
    }

    /// Resolve a composition clock: the default clock is the fixed 5/5
    /// wave; "<path>$CLK_OUT" names a ClockGen (periodic) or a dynamic
    /// clock prim (MakeClock/ClockDiv/ClockInverter, prim-triggered
    /// edges); interface output clocks and input clock ports chase
    /// through ifc_clocks / instantiation bindings to their oscillator;
    /// noClock and non-default top input clocks never fire.
    fn resolve_source(&self, clock: StrId) -> ClockSource {
        if Some(clock) == self.d.default_clock {
            return Self::default_wave();
        }
        let name = self.s(clock).to_string();
        self.resolve_clock_at(0, &name)
    }

    /// Resolve a clock wire name relative to an instance.
    fn resolve_clock_at(&self, inst: usize, wire: &str) -> ClockSource {
        // prim-driven clocks register absolute "<abs.path>$CLK_OUT" keys
        let abs = {
            let base = &self.insts[inst].path;
            if base.is_empty() {
                wire.to_string()
            } else {
                format!("{base}.{wire}")
            }
        };
        if let Some(w) = self.clockgen_waves.get(&abs) {
            return ClockSource::Wave(*w);
        }
        if let Some(&init_high) = self.dynclk_init.get(&abs) {
            let path = abs.strip_suffix("$CLK_OUT").unwrap_or(&abs);
            let driver = *self
                .inst_by_path
                .get(path)
                .unwrap_or_else(|| panic!("unknown clock driver {path:?}"));
            return ClockSource::Triggered { init_high, driver };
        }
        // child-qualified wire ("i$CLK_outclk", "a.b$CLK_x"): resolve
        // inside the child instance
        if let Some(k) = wire.rfind('$') {
            let (qual, base) = (&wire[..k], &wire[k + 1..]);
            let cpath = if self.insts[inst].path.is_empty() {
                qual.to_string()
            } else {
                format!("{}.{}", self.insts[inst].path, qual)
            };
            if let Some(&ci) = self.inst_by_path.get(&cpath) {
                return self.resolve_clock_at(ci, base);
            }
            panic!("trs-interp: unimplemented clock source {wire:?} (P1 bring-up)");
        }
        // top-level wires: the default clock name resolves to the fixed
        // wave; other top input clocks have no waveform and never fire
        let module = self.module_of(inst);
        let mir = self.mods[module].ir;
        if self.insts[inst].path.is_empty() {
            if let Some(dc) = self.d.default_clock {
                if self.s(dc) == wire {
                    return Self::default_wave();
                }
            }
        }
        // interface output clock of this module: follow the internal wire
        if let Some((_, osc)) = self.d.modules[mir]
            .ifc_clocks
            .iter()
            .find(|(n, _)| self.s(*n) == wire)
        {
            return match osc {
                Expr::Port(p) => {
                    let inner = self.s(*p).to_string();
                    self.resolve_clock_at(inst, &inner)
                }
                _ => ClockSource::Never, // constant = noClock
            };
        }
        // input clock port: chase the parent's instantiation binding
        if let InstKind::User { clk_binds, .. } = &self.insts[inst].kind {
            if let Some((owner, osc)) =
                clk_binds.iter().find(|(k, _)| self.s(**k) == wire).map(|(_, v)| v)
            {
                return match osc {
                    Expr::Port(p) => {
                        let inner = self.s(*p).to_string();
                        self.resolve_clock_at(*owner, &inner)
                    }
                    _ => ClockSource::Never,
                };
            }
        }
        // a top input clock port that is not the default clock: defined
        // with period 0, never ticks
        if self.insts[inst].path.is_empty()
            && self.d.modules[mir]
                .inputs
                .iter()
                .any(|p| p.kind == ir::PortKind::Clock && self.s(p.name) == wire)
        {
            return ClockSource::Never;
        }
        panic!("trs-interp: unimplemented clock source {wire:?} (P1 bring-up)");
    }

    /// Run until $finish or the cycle limit.  Returns the exit code.
    ///
    /// Multi-clock event loop: each composition fires on one (clock, edge);
    /// clock waveforms come from resolve_wave.  Same-time edges execute in
    /// clock definition order (the kernel breaks ties by clock handle
    /// index).  max_cycles counts default-clock posedges, including the
    /// in-reset edge at t=0.
    pub fn run(&mut self, max_cycles: u64) -> i32 {
        let comps = self.d.compositions.clone();

        // distinct clocks in first-appearance order
        let mut clocks: Vec<StrId> = Vec::new();
        for c in &comps {
            if !clocks.contains(&c.clock) {
                clocks.push(c.clock);
            }
        }
        let sources: Vec<ClockSource> =
            clocks.iter().map(|&c| self.resolve_source(c)).collect();
        // clock-driver prim instance -> clock index, for routing triggered
        // edges after ticks
        let driver_clock: HashMap<usize, usize> = sources
            .iter()
            .enumerate()
            .filter_map(|(ci, s)| match s {
                ClockSource::Triggered { driver, .. } => Some((*driver, ci)),
                _ => None,
            })
            .collect();

        // pre-resolve each composition: (clock idx, entries, inhibitors,
        // ticks)
        struct RComp {
            clk: usize,
            posedge: bool,
            // (instance idx, module idx, domain, segment idx)
            entries: Vec<(usize, usize, u32, usize)>,
            cross: HashMap<(usize, StrId), Vec<(usize, StrId)>>,
            // (prim instance, port, is_reset_tick, owner instance for
            // gate evaluation, gate expr)
            ticks: Vec<(usize, StrId, bool, usize, Option<Expr>)>,
            // clock-crossing "early" rules: excluded from the edge pass,
            // run in the after-edge pass at end of timeslice (the C++
            // schedule_after_posedge_* at PG_FINAL)
            early: std::collections::HashSet<(usize, StrId)>,
        }
        let rcomps: Vec<RComp> = comps
            .iter()
            .map(|comp| {
                let entries = comp
                    .entries
                    .iter()
                    .map(|e| {
                        let path = self.s(e.instance).to_string();
                        let ii = *self
                            .inst_by_path
                            .get(&path)
                            .unwrap_or_else(|| panic!("unknown instance path {path:?}"));
                        (ii, self.module_of(ii), e.domain, e.segment as usize)
                    })
                    .collect();

                // cross-inhibit lookup: (later inst, later rule) -> earlier CFs
                let mut cross: HashMap<(usize, StrId), Vec<(usize, StrId)>> = HashMap::new();
                for (earlier, later) in &comp.cross_inhibits {
                    let (e_inst, e_rule) = self.split_qual(*earlier);
                    let (l_inst, l_rule) = self.split_qual(*later);
                    let e_mod = self.module_of(e_inst);
                    let e_mir = self.mods[e_mod].ir;
                    let e_ri = self.mods[e_mod].rules[&e_rule];
                    let e_cf = self.d.modules[e_mir].rules[e_ri].can_fire;
                    cross.entry((l_inst, l_rule)).or_default().push((e_inst, e_cf));
                }

                let ticks = comp
                    .ticks
                    .iter()
                    .map(|tk| {
                        let ipath = self.s(tk.instance).to_string();
                        let ppath = if ipath.is_empty() {
                            self.s(tk.prim).to_string()
                        } else {
                            format!("{}.{}", ipath, self.s(tk.prim))
                        };
                        let ii = *self
                            .inst_by_path
                            .get(&ppath)
                            .unwrap_or_else(|| panic!("unknown tick instance {ppath:?}"));
                        let owner = *self.inst_by_path.get(&ipath).unwrap_or(&0);
                        (ii, tk.port, tk.reset, owner, tk.gate.clone())
                    })
                    .collect();

                let early = comp
                    .early
                    .iter()
                    .map(|q| self.split_qual(*q))
                    .collect();

                RComp {
                    clk: clocks.iter().position(|&c| c == comp.clock).unwrap(),
                    posedge: comp.posedge,
                    entries,
                    cross,
                    ticks,
                    early,
                }
            })
            .collect();

        // event heap over (time, priority, clock idx, is_posedge);
        // priority 0 = one-shot initial edges (PG_INITIAL), 1 = regular
        // waveform/triggered edges (PG_LOGIC) — initial edges run first
        // within a timeslice and never period-reschedule
        use std::cmp::Reverse;
        use std::collections::BinaryHeap;
        let mut heap: BinaryHeap<Reverse<(u64, u8, usize, bool)>> = BinaryHeap::new();
        for (ci, src) in sources.iter().enumerate() {
            let need_pos = rcomps.iter().any(|r| r.clk == ci && r.posedge);
            let need_neg = rcomps.iter().any(|r| r.clk == ci && !r.posedge);
            match src {
                ClockSource::Wave(w) => {
                    let first_pos = if w.init_high { w.delay + w.lo } else { w.delay };
                    let first_neg = if w.init_high { w.delay } else { w.delay + w.hi };
                    if need_pos {
                        heap.push(Reverse((first_pos, 1, ci, true)));
                    }
                    if need_neg {
                        heap.push(Reverse((first_neg, 1, ci, false)));
                    }
                    // has_initial_value: an extra t=0 edge toward the
                    // initial value, before regular t=0 edges
                    let dir = w.init_high;
                    if w.has_init && ((dir && need_pos) || (!dir && need_neg)) {
                        heap.push(Reverse((0, 0, ci, dir)));
                    }
                }
                ClockSource::Triggered { init_high, .. } => {
                    // bk_enqueue_initial_clock_edge: one edge at t=0 in the
                    // direction of the initial value; later edges come from
                    // the driving prim
                    let dir = *init_high;
                    if (dir && need_pos) || (!dir && need_neg) {
                        heap.push(Reverse((0, 0, ci, dir)));
                    }
                }
                ClockSource::Never => {}
            }
        }

        // kernel reset protocol: top reset asserted before time 0;
        // InitialReset outputs assert from time 0 as well (reset_init)
        self.apply_reset(0, true);
        let inits = std::mem::take(&mut self.initial_asserts);
        for n in inits {
            self.apply_reset(n, true);
        }
        self.flush_reset_pending();

        // (clock,edge) compositions that fired in the current timeslice,
        // for the after-edge (PG_FINAL) pass
        let mut fired_this_slice: Vec<usize> = Vec::new();

        while self.finished.is_none() {
            let Some(Reverse((t, prio, ci, pos))) = heap.pop() else { break };
            // top reset deasserts at t=2 after that instant's logic
            if t > 2 && self.rst_asserted[0] {
                self.apply_reset(0, false);
                self.flush_reset_pending();
            }
            if pos && Some(clocks[ci]) == self.d.default_clock {
                if self.cycle >= max_cycles {
                    break;
                }
                self.cycle += 1;
            }
            self.now = t;

            for (rci, rc) in rcomps
                .iter()
                .enumerate()
                .filter(|(_, r)| r.clk == ci && r.posedge == pos)
            {
                fired_this_slice.push(rci);
                // fresh latch space for this edge
                for i in 0..self.insts.len() {
                    if let InstKind::User { latched, .. } = &mut self.insts[i].kind {
                        latched.clear();
                    }
                }

                for &(inst, module, domain, seg) in &rc.entries {
                    let mir = self.mods[module].ir;
                    let sched = &self.d.modules[mir].schedule;
                    let ms = sched
                        .domains
                        .iter()
                        .find(|ms| ms.domain == domain && ms.posedge == rc.posedge)
                        .or_else(|| sched.domains.iter().find(|ms| ms.domain == domain))
                        .unwrap_or_else(|| {
                            panic!(
                                "no schedule for domain {domain} in {:?}",
                                self.s(self.d.modules[mir].name)
                            )
                        });
                    let nodes: Vec<SchedNode> = ms.segments[seg].nodes.clone();
                    for node in nodes {
                        if self.finished.is_some() {
                            break;
                        }
                        // clock-crossing rules run in the after-edge pass
                        let r0 = match node {
                            SchedNode::Sched(r) | SchedNode::Exec(r) => r,
                        };
                        if rc.early.contains(&(inst, r0)) {
                            continue;
                        }
                        match node {
                            SchedNode::Sched(r) => {
                                let ci2 = rc.cross.get(&(inst, r)).cloned().unwrap_or_default();
                                self.latch_rule(inst, r, &ci2);
                            }
                            SchedNode::Exec(r) => self.exec_rule(inst, r),
                        }
                    }
                }

                // end-of-edge ticks (reset ticks are conditional: the
                // prim itself checks its reset line)
                for (inst, port, is_rst, owner, gexpr) in rc.ticks.clone() {
                    let gate = match &gexpr {
                        None => true,
                        Some(g) => {
                            let mut c = Ctx::default();
                            self.eval(owner, &mut c, g).as_bool()
                        }
                    };
                    if let InstKind::Prim(p) = &mut self.insts[inst].kind {
                        if is_rst {
                            if gate {
                                p.rst_tick(t);
                            }
                        } else {
                            let pname = self.d.strings[port as usize].clone();
                            p.tick(&pname, t, pos, gate);
                        }
                    }
                    if self.rstgen_out.contains_key(&inst) {
                        self.poll_rstgen(inst);
                    }
                    // clock-generating prims trigger output edges at the
                    // current instant
                    if let Some(&out_ci) = driver_clock.get(&inst) {
                        let edges = if let InstKind::Prim(p) = &mut self.insts[inst].kind {
                            p.take_clock_edges()
                        } else {
                            Vec::new()
                        };
                        for pos_edge in edges {
                            heap.push(Reverse((t, 1, out_ci, pos_edge)));
                        }
                    }
                }
            }

            // regular waveform edges self-reschedule one period out;
            // initial edges are one-shot (kernel: PG_INITIAL doesn't repeat)
            if prio != 0 {
                if let ClockSource::Wave(w) = &sources[ci] {
                    heap.push(Reverse((t + w.hi + w.lo, 1, ci, pos)));
                }
            }

            // end of timeslice: apply deferred reset transitions, then run
            // the after-edge pass (clock-crossing "early" rules sample
            // post-edge, post-reset state — kernel PG_FINAL, after
            // PG_AFTER_LOGIC reset flushing)
            let same_time = matches!(heap.peek(), Some(Reverse((nt, _, _, _))) if *nt == t);
            if !same_time {
                self.flush_reset_pending();
                for rci in std::mem::take(&mut fired_this_slice) {
                    let rc = &rcomps[rci];
                    if rc.early.is_empty() {
                        continue;
                    }
                    for &(inst, module, domain, seg) in &rc.entries {
                        let mir = self.mods[module].ir;
                        let sched = &self.d.modules[mir].schedule;
                        let ms = sched
                            .domains
                            .iter()
                            .find(|ms| ms.domain == domain && ms.posedge == rc.posedge)
                            .or_else(|| {
                                sched.domains.iter().find(|ms| ms.domain == domain)
                            })
                            .unwrap();
                        let nodes: Vec<SchedNode> = ms.segments[seg].nodes.clone();
                        for node in nodes {
                            if self.finished.is_some() {
                                break;
                            }
                            let r0 = match node {
                                SchedNode::Sched(r) | SchedNode::Exec(r) => r,
                            };
                            if !rc.early.contains(&(inst, r0)) {
                                continue;
                            }
                            match node {
                                SchedNode::Sched(r) => {
                                    let ci2 = rc
                                        .cross
                                        .get(&(inst, r))
                                        .cloned()
                                        .unwrap_or_default();
                                    self.latch_rule(inst, r, &ci2);
                                }
                                SchedNode::Exec(r) => self.exec_rule(inst, r),
                            }
                        }
                    }
                }
            }

            // the cycle limit stops the simulation at the Nth default
            // posedge, but the kernel finishes the current timeslice
            // first — same-instant edges of other clocks still run;
            // events at later times do not
            if self.cycle >= max_cycles && !same_time {
                break;
            }
        }
        // bluesim.tcl: exit 1 iff $fatal was called; $finish status codes
        // do not surface as process exit codes
        if self.fataled { 1 } else { 0 }
    }

    /// "a.b.RL_r" -> (instance index of "a.b", rule StrId of "RL_r")
    fn split_qual(&mut self, q: StrId) -> (usize, StrId) {
        let s = self.s(q).to_string();
        let (ipath, rname) = match s.rfind('.') {
            Some(k) => (&s[..k], &s[k + 1..]),
            None => ("", s.as_str()),
        };
        let inst = *self
            .inst_by_path
            .get(ipath)
            .unwrap_or_else(|| panic!("unknown instance {ipath:?}"));
        // find the StrId for the local rule name
        let rid = self
            .d
            .strings
            .iter()
            .position(|x| x == rname)
            .unwrap_or_else(|| panic!("unknown rule name {rname:?}"))
            as StrId;
        (inst, rid)
    }
}

/// dollar_display's Target collects errors with push_front and prints
/// them after the task output: "Output error: <msg>", newest first.
fn emit_output_errors(errs: &[String]) {
    for e in errs.iter().rev() {
        print!("Output error: {e}");
    }
}

fn cookie_key(cookie: u32) -> StrId {
    // cookies live in a synthetic key space far above real string ids
    0x8000_0000 | cookie
}

pub fn run_file(path: &str, max_cycles: u64, plusargs: &[String]) -> Result<i32, String> {
    let bytes = std::fs::read(path).map_err(|e| format!("{path}: {e}"))?;
    let design = Design::decode(&bytes).map_err(|e| e.to_string())?;
    let mut interp = Interp::new(design);
    interp.plusargs = plusargs.to_vec();
    // user BDPI code lives in a companion shared object next to the .bir
    let so = path.strip_suffix(".bir").unwrap_or(path).to_string() + ".bdpi.so";
    if std::path::Path::new(&so).exists() {
        interp.load_bdpi(&so)?;
    }
    Ok(interp.run(max_cycles))
}
