package Letrecmod(sysLetrecmod) where

import List

recMap :: (a -> b) -> List a -> List b
recMap f Nil = Nil
recMap f (Cons x xs) = Cons (f x) (recMap f xs)

seven :: Integer
seven = let evens :: List Integer
            evens = cons 0 (recMap ((+) 1) odds)
            odds  :: List Integer = recMap ((+) 1) evens
        in odds !! 3

sysLetrecmod :: Module Empty
sysLetrecmod =
  module
    rules
      when True ==>
         action
            $display seven
            $finish 0
