package Letrec3(sysLetrec3) where

import List

recMap :: (a -> b) -> List a -> List b
recMap f Nil = Nil
recMap f (Cons x xs) = Cons (f x) (recMap f xs)

eleven :: Integer
eleven = let
            evens :: List Integer
            evens = cons 0 (recMap ((+) 1) treys)
            odds  :: List Integer = recMap ((+) 1) evens
            treys :: List Integer
            treys = recMap ((+) 1) odds
        in treys !! 3

sysLetrec3 :: Module Empty
sysLetrec3 =
  module
    rules
      when True ==>
         action
            $display eleven
            $finish 0
